### ISSUE TITLE
NotSupported error while serializing a normal struct

### ISSUE THREAD

**Issue by GopherJ** [risc0/risc0#1012]
```rust
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Input {
    pub transactions: Vec<Transaction>,
    pub block: Block,
    pub state: State,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct BlockHeader {
    pub number: u32,
    pub parent_hash: B256,
    pub state_root: B256,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Block {
    pub header: BlockHeader,
    pub hash: B256,
    pub transactions: Vec<Transaction>,
    #[serde(with = "ts_seconds")]
    pub timestamp: NaiveDateTime,
}

#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct State {
    #[serde(flatten)]
    pub asset_manager: AssetManager,
    #[serde(flatten)]
    pub market_manager: MarketManager,
    #[serde(flatten)]
    pub account_manager: AccountManager,
    pub counter: StateCounter,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AssetManager {
    pub assets: HashMap<String, Asset>,
}

#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct MarketManager {
    pub markets: HashMap<MarketId, Market>,
}

#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct AccountManager {
    pub accounts: HashMap<String, Account>,
}

...
```

I got some issues to serialize the `Input` struct, all I did is just calling `to_vec` in guest

**Comment by SchmErik** [comment]
Could you provide the actual error message and the line of code that causes the error?

**Comment by GopherJ** [comment]
@SchmErik it outputs this error while calling `to_vec`:

```
    let env = ExecutorEnv::builder()
        .add_input(&to_vec(&input).unwrap())
        .build()
        .unwrap();
```

here `input` is the above `Input` struct which contains block and state

**Comment by GopherJ** [comment]
```
[host/src/subcommand/prover.rs:45] 5 = 5
[/home/cj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-0.18.0/src/serde/serializer.rs:292] 2 = 2
thread 'main' panicked at host/src/subcommand/prover.rs:57:36:
called `Result::unwrap()` on an `Err` value: NotSupported
stack backtrace:
   0:     0x55f04be7614c - <unknown>
   1:     0x55f04bea6180 - <unknown>
   2:     0x55f04be72c0f - <unknown>
   3:     0x55f04be75f34 - <unknown>
   4:     0x55f04be77767 - <unknown>
   5:     0x55f04be774aa - <unknown>
   6:     0x55f04be77c48 - <unknown>
   7:     0x55f04be77b31 - <unknown>
   8:     0x55f04be76666 - <unknown>
   9:     0x55f04be77862 - <unknown>
  10:     0x55f049bbaa65 - <unknown>
  11:     0x55f049bbb093 - <unknown>
  12:     0x55f049c279fa - <unknown>
  13:     0x55f049c8df6b - <unknown>
  14:     0x55f049c8c60d - <unknown>
  15:     0x55f049c967e3 - <unknown>
  16:     0x55f049d01a23 - <unknown>
  17:     0x55f049d012e3 - <unknown>
  18:     0x55f049d01fe2 - <unknown>
  19:     0x55f049c96281 - <unknown>
  20:     0x55f049d45190 - <unknown>
  21:     0x55f049c96232 - <unknown>
  22:     0x55f049c0f429 - <unknown>
  23:     0x55f049cdba3f - <unknown>
  24:     0x55f049d1ee12 - <unknown>
  25:     0x55f049d33dbd - <unknown>
  26:     0x55f049d3c4f6 - <unknown>
  27:     0x55f04be68a05 - <unknown>
  28:     0x55f049d3c4ca - <unknown>
  29:     0x55f049cdbaee - <unknown>
  30:     0x7f67488bbd90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  31:     0x7f67488bbe40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  32:     0x55f049bbb3f5 - <unknown>
  33:                0x0 - <unknown>
[Finished running. Exit status: 101]
```

**Comment by GopherJ** [comment]
After applying some great suggestions from risc0 team members: @tim @SchmErik by commenting out:

```
   #[serde(with = "ts_seconds")]
    pub timestamp: NaiveDateTime,
```

it seems working better, another issue is raised now, the code freezes on the following line:

```
    let env = ExecutorEnv::builder().add_input(&to_vec(&input)?).build()?;
```

from the logs I can see it's trying to serialize but is doing it very slowly

![image](https://github.com/risc0/risc0/assets/33961674/74b24759-54ff-4d26-a960-ee53e254d676)

**Comment by GopherJ** [comment]
Also FYI, I didn't run in release mode, though I tried to run in release mode once and it doesn't seem to change anything

**Comment by GopherJ** [comment]
Do you have docs about optimisation? I can apply them first to see if it changes anything

**Comment by GopherJ** [comment]
I also tried to enable `cuda` feature and my PC has nvidia-4090, but it seems cannot find my cuda installation (I used to run scroll prover so the installation should be ok, but I recently updated some packages so I dont know if that influence)

**Comment by SchmErik** [comment]
> Do you have docs about optimisation? I can apply them first to see if it changes anything

Did you try replacing HashMap with [BTreeMap](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html)?

**Comment by SchmErik** [comment]
> I also tried to enable `cuda` feature and my PC has nvidia-4090, but it seems cannot find my cuda installation (I used to run scroll prover so the installation should be ok, but I recently updated some packages so I dont know if that influence)

Could you describe what you did to enable it and any error messages generated? When you try to run with this feature enabled?

**Comment by GopherJ** [comment]
@SchmErik FYI I fixed this by doing:



- remove #[serde(untagged)]
- change rust_decimal to use serde-str feature
- remove #[serde(flatten)]

**Comment by GopherJ** [comment]
> > I also tried to enable `cuda` feature and my PC has nvidia-4090, but it seems cannot find my cuda installation (I used to run scroll prover so the installation should be ok, but I recently updated some packages so I dont know if that influence)
> 
> Could you describe what you did to enable it and any error messages generated when you try to run with this feature enabled?

I'm using v0.18.0 and I just enabled it the following way:

```
cuda    = ["risc0-zkvm/cuda", "risc0-zkp/cuda"]
default = ["cuda"]
```

then I try to compile, but it will output the cuda error then

**Comment by GopherJ** [comment]
> > Do you have docs about optimisation? I can apply them first to see if it changes anything
> 
> Did you try replacing HashMap with [BTreeMap](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html)?

Do I also need to replace HashSet, I believe yes
