### ISSUE TITLE
feature: concrete security calculator

### ISSUE THREAD

**Issue by pdg744** [risc0/risc0#1018]
## Goal
Add terminal output to indicate security level for zkVM proofs, in terms of "proven security" and "conjectured security"

## References
[Ulvetanna's analysis - PDF](https://drive.google.com/file/d/1tuY4QbuMJ5Oe6oIvGVlipZWSfjjq1XFV/view?usp=sharing)
[Ulvetanna's analysis - python notebook](https://github.com/pdg744/FRI-Analysis)
[Miden's calculator](https://github.com/facebook/winterfell/blob/4d5157bb77e368db24094e80a1f006aa5b8eca70/air/src/proof/mod.rs#L100)
[RISC Zero ZKP Whitepaper](https://dev.risczero.com/proof-system-in-detail.pdf)

## Work in progress
Ying Tong is working on this [here](https://github.com/risc0/risc0/compare/main...therealyingtong:risc0:soundness?expand=1)

**Comment by pdg744** [comment]
We landed a first version of the calculator (with some known issues) in #1593 and are working on further updates in #1661

**Comment by SchmErik** [comment]
looks like this has been complete so I'm going to close it. Feel free to reopen if that's not the case...

**Comment by pdg744** [comment]
Yes indeed -- the soundness calculator is done and lives here: https://github.com/risc0/risc0/blob/main/risc0/zkp/src/prove/soundness.rs

**Comment by pdg744** [comment]
I guess there are a few lower priority action items here:
 - Document how to turn on the calculator 
 - Move the calculator to live on the verifier side rather than the prover side
