### ISSUE TITLE
cannot find cuda installation

### ISSUE THREAD

**Issue by GopherJ** [risc0/risc0#1022]
thread 'main' panicked at /home/cj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/find_cuda_helper-0.2.0/src/lib.rs:12:13:
  Could not find a cuda installation

**Comment by GopherJ** [comment]
I have nvidia-cuda-toolkit and nvidia-driver-535 installed

**Comment by flaub** [comment]
This might just be that the PATH needs to include `/usr/local/cuda/bin`.

**Comment by sgaure** [comment]
Since I just struggled with this problem. 

It turns out that `find_cuda_helper` looks in `/opt/cuda` and `/usr/local/cuda` for `include/cuda.h`. However, my cuda is in `/usr`, so a `ln -s /usr /usr/local/cuda` did the trick.

**Comment by pdg744** [comment]
i'm going to close this because there's not enough information included to reproduce your error. 

@GopherJ -- if you're still looking for support on this, please re-open with more information. we have issue templates here to help with that: https://github.com/risc0/risc0/issues/new/choose
