### ISSUE TITLE
Fix "Hello world" example

### ISSUE THREAD

**Issue by microbecode** [risc0/risc0#1023]
I'm new to the ecosystem.

The Hello World example at https://github.com/risc0/risc0/blob/main/examples/hello-world/tutorial.md uses outdated code. I got the example working only after digging a bit and finding https://github.com/risc0/risc0/blob/v0.18.0/examples/hello-world/methods/guest/src/main.rs , which has working code.

Please update the Hello World documentation - it's the first thing new developers try to implement. For example the `.write(&a).unwrap()` is outdated in `ExecutorEnv`.

**Comment by flaub** [comment]
Thanks for your feedback. Actually we just recently moved to using `write`, so what you're seeing is pre-released examples. If you want to see the latest examples, the links from our dev docs site should point to the latest stable version: https://github.com/risc0/risc0/tree/v0.18.0/examples/hello-world

**Comment by microbecode** [comment]
Ah, so it was the other way around. Same result, from my point of view :)

Thanks!

**Comment by flaub** [comment]
I think the solution to this is to migrate the `tutorial.md` over into the `website` directory. We could also mention in READMEs on how whatever is on `main` is considered unreleased and not ready for use yet, and we could put a link to the latest stable version.

**Comment by it09** [comment]
Could you please also 

- automate [Step 2](https://github.com/risc0/risc0/blob/1cc087f5e99273b5e32d5ca7204526b7223376f6/examples/hello-world/tutorial.md#step-2-give-the-methods-package-a-name) 
- [Step 3](https://github.com/risc0/risc0/blob/1cc087f5e99273b5e32d5ca7204526b7223376f6/examples/hello-world/tutorial.md#step-3-give-the-guest-program-and-its-packages-a-name)
-  In host/src/main.rs, there is missing `serde::{from_slice, to_vec},` in  `use risc0_zkvm::{  ...  };`

**Comment by flaub** [comment]
I believe both steps are in progress here: https://github.com/risc0/risc0/pull/1032

**Comment by flaub** [comment]
cc: @carterbrett

**Comment by flaub** [comment]
The new API will drop the need for `to_vec`, and we plan to drop the need for `from_slice` as well.

**Comment by flaub** [comment]
Related: #1036

**Comment by flaub** [comment]
Fixed with #1077
