### ISSUE TITLE
Enable easy access to cycle count, segment count, and executor time stats from running dev-mode

### ISSUE THREAD

**Issue by Cardosaum** [risc0/risc0#1027]
A feature is proposed to simplify the process for users to view cycle count, segment count, and executor time statistics when running in development mode. By setting `RISC0_DEV_MODE=1` and `RUST_LOG="<module>=debug"`, a clear log of executor stats should be enabled. This feature aims to enhance the user experience by providing an easier way to obtain statistics about the program running.

**Comment by SchmErik** [comment]
So what we discussed was to put something like this in the template:
https://github.com/risc0/risc0/blob/2a7e912094fd4d78a793ec36076cab236ccff958/examples/zkevm-demo/src/main.rs#L43
This uses env_logger but we might want tracing subscriber instead.

And then, add `log::info!(...);` in the executor somewhere in this function: https://github.com/risc0/risc0/blob/d1b7a5ed5fae4a4a1ae33d3523b8078b959e9f5b/risc0/zkvm/src/host/server/exec/executor.rs#L256
