### ISSUE TITLE
verify SnarkReceipt locally?

### ISSUE THREAD

**Issue by GopherJ** [risc0/risc0#1060]
seems we can only use Risc0Verifier to verify SnarkReceipt, is it possible to do it locally? do you already have a rust version grouth16 verifier? 

bottom line a fast solution is maybe to run revm with Risc0Verifier

**Comment by mothran** [comment]
We don't currently have a Rust SNARK verifier, but it is something were aware is missing. 

If you need a spot check I normally ingest the SNARK data into a foundry unit test in solidity to run the verifier.

**Comment by flaub** [comment]
Some progress has been made: https://github.com/risc0/risc0/pull/1158

Upcoming PRs will provide an end 2 end solutino

**Comment by flaub** [comment]
WIP: https://github.com/risc0/risc0/pull/1356

**Comment by SchmErik** [comment]
this has been implemented and available on x86 with docker. closing.
