### ISSUE TITLE
bonsai sdk is using blocking reqwest which makes it panic in tokio runtime

### ISSUE THREAD

**Issue by GopherJ** [risc0/risc0#1062]
Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.

**Comment by mothran** [comment]
We have a work around at: https://github.com/risc0/risc0/blob/main/bonsai/sdk/src/lib.rs#L22 you can enable the `async` flag. Would that be a reasonable workaround?

**Comment by GopherJ** [comment]
yes thanks @mothran I found that after raising the issue
