### ISSUE TITLE
`risc0-zkp-accel` 0.4.0 build failed on docs.rs

### ISSUE THREAD

**Issue by LoganDark** [risc0/risc0#107]
I was monitoring the docs.rs recent build failures and noticed that `risc0-zkp-accel` 0.4.0 is failing because it attempts to access the network in its build script: https://docs.rs/crate/risc0-zkp-accel/0.4.0

It should be sufficient to omit the network accesses when the crate is being built by docs.rs. You can check for the [`DOCS_RS` environment variable](https://docs.rs/about/builds#detecting-docsrs) and skip the network access, or just fail gracefully without panicking.

(In fact, it seems like a lot of your crates are failing to build, such as `risc0-zkvm-host-sys`, `risc0-zkvm-prove`, and `risc0-zkvm-host`.)

**Comment by flaub** [comment]
At least one crate (`tbb`) needs to download the source so it needs network access. It's also the case that pretty much all the `-sys` crates depend on `tbb` so they will all need network access?

**Comment by LoganDark** [comment]
> needs to download the source

This isn't typical for Rust crates. Usually the source is included in the crate itself, and able to be redirected using environment variables. Is there any reason `tbb` needs to do it this way?

**Comment by flaub** [comment]
I think this is similar to openssl. My understanding is that there's an internal `openssl-src` crate that pulls down the source from some other location.

TBB is a project maintained by Intel. Currently much of our code is written in C++ with a plan to eventually port it to rust. But at the moment, TBB is a C++-only dependency. I also felt like doing it this way was better on developers than having them do `apt install libtbb` or whatnot.

**Comment by LoganDark** [comment]
> I think this is similar to openssl. My understanding is that there's an internal `openssl-src` crate that pulls down the source from some other location.
> 
> TBB is a project maintained by Intel. Currently much of our code is written in C++ with a plan to eventually port it to rust. But at the moment, TBB is a C++-only dependency. I also felt like doing it this way was better on developers than having them do `apt install libtbb` or whatnot.

What I'm saying is that binding crates often include the library they're binding to, which they may or may not have written, in the crate itself. It's called vendoring and it allows `docs.rs` to generate documentation for your crate, among other things.

**Comment by flaub** [comment]
OK, so you're saying we should just vendor the TBB project?

If possible I'd like to try to avoid doing that. Is there no other way to make docs.rs builds work?

**Comment by LoganDark** [comment]
> Is there no other way to make docs.rs builds work?

`docs.rs` does not give network access to any crate. If you really don't want to vendor TBB, you can precompile the bindings and make the build script use those instead of downloading the source when the crate is being built in docs.rs. But this will still make a weird user experience when a crate build script suddenly initiates a separate download that could have been included in the crate itself. I'm not sure whether it's frowned upon or not but I would assume it is.

**Comment by LoganDark** [comment]
> I think the issue here is that there are no 'bindings' exposed by TBB, because it's a purely C++ dependency. In other words, it's a dependency from one C++ library to another (no rust involved at all). I'm just using the cargo system to make it much easier for developers to make use of higher level rust bindings.

 The issue is that you're downloading TBB at compile time, which is wrong (TBB should be included in the cargo download). You should vendor it whether or not you use it directly from Rust, but just avoiding the download on Docs.rs would indeed fix the build.
