### ISSUE TITLE
Docs: write docs on continuations

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#1071]
Write a doc for continuations. Describe the problem, and how it's solved, etc. This is an internal feature that's enabled automatically but it's good to have a description. Target audience is people who might be familiar with other proving systems.

**Comment by tzerrell** [comment]
It's not the same content as documentation, but my news post on this might be helpful to draw from in places when writing these docs: https://www.risczero.com/news/continuations

**Comment by SchmErik** [comment]
Sorry for the noise - so I Brett asked me to write a short overview of continuations as a part of the zkvm overview and when I opened this, I was intending on this being a tracking issue for that. The PR for this small overview is #1101 but let's just use this issue to track the continuations document anyway.

**Comment by SchmErik** [comment]
In order to build up the notion of continuations in a way that people can understand at a deeper level, here's a list of concepts used:

- cycles
- page fault

**Comment by nategraf** [comment]
Do we believe this addressed by https://github.com/risc0/risc0/pull/1314 and https://github.com/risc0/risc0/pull/1274? Together, the example, terminology, and docs on the relevant Rust methods and types consistent the implemented documentation. The only other planned item of documentation is a study club talk.

**Comment by tzerrell** [comment]
> Do we believe this addressed by https://github.com/risc0/risc0/pull/1314 and https://github.com/risc0/risc0/pull/1274?

Personally, between those and #1101 (and the blog post #1101 references) I think our docs here are probably adequate. Open to suggestions about what's not sufficiently covered if I'm wrong though.

**Comment by SchmErik** [comment]
I think we could close this. @carterbrett what do you think?

**Comment by SchmErik** [comment]
Looked more closely at @nategraf's PRs and I think this is sufficient to close. @carterbrett Feel free to reopen if there's more discussion needed though.
