### ISSUE TITLE
bonsai feature gate to use rustls

### ISSUE THREAD

**Issue by GopherJ** [risc0/risc0#1073]

**Comment by flaub** [comment]
Can you provide more details on this issue? If you could provide use cases, reproduction examples, and expected results that would help out a lot.

**Comment by GopherJ** [comment]
hi @flaub sorry for missing use cases, I was trying to build a static linked binary and rustls sounds better in this case.

**Comment by flaub** [comment]
Switched to `rustls` in https://github.com/risc0/risc0/pull/1200
