### ISSUE TITLE
[Comments Requested] Update Datasheet

### ISSUE THREAD

**Issue by tzerrell** [risc0/risc0#1083]
With @capossele's updates to the datasheet in https://github.com/risc0/risc0/pull/897 (:tada:!), we should update the website to link to these new figures rather than the older datasheet. I see a few ways to do it, and am interested in feedback on which approach to take:

* Directly link to the datasheet at https://risc0.github.io/ghpages/datasheet/index.html as it currently exists. The easiest thing to do, this shows everyone the very latest numbers.
* Make a long term copy of the datasheet upon each version release, and link these "released datasheet"s on our website. Shows our users consistent numbers coming from a stable version, requires a bit of engineering in https://github.com/risc0/ghpages
* Manually copy the datasheet numbers into a "pretty" datasheet format (e.g. like what we have in https://dev.risczero.com/datasheet.pdf) at each version release. Gives easier flexibility and adaptability around formatting, requires manual work (and potentially introduces manual error) on each release.

That's in my preference order (i.e. I like just directly linking the most) but I definitely see arguments for each of these. Anyone else have their own feedback or preferences?

**Comment by flaub** [comment]
I'm going to get the datasheet to be updated, but I still think we should have a separate release process for the datasheet for public consumption.
