### ISSUE TITLE
Update examples on github to use installation page

### ISSUE THREAD

**Issue by flaub** [risc0/risc0#1088]
@tzerrell Not sure whether we want to reopen https://github.com/risc0/website/pull/286 or call this a separate issue

**Comment by SchmErik** [comment]
So I'm looking at how to `#include(install.md)` or something like that and there's no native support for this. However, we could use something like m4 preprocessor or pandoc for this

**Comment by flaub** [comment]
I think just having a link is fine for examples.

**Comment by tzerrell** [comment]
> @tzerrell Not sure whether we want to reopen [risc0/website#286](https://github.com/risc0/website/pull/286) or call this a separate issue

Since risc0/website#286 is a PR and has already been merged I think we do need this as a separate issue
