### ISSUE TITLE
Convert READMEs and tutorials to rust docs

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#1098]
This will allow any code that appears in readme's to run under CI

**Comment by lazyfuhrer** [comment]
Hi, I want to give it a try. Can you tell me what are the READMEs and tutorials need to be converted ? @SchmErik

**Comment by flaub** [comment]
I think this is complete?

**Comment by SchmErik** [comment]
So the hello world tutorial is now under the tutorials - are we running the codes snippet of this in CI? IIRC, I mentioned converting to rust docs because there was an idea that was floated that there were ways to run this in CI if we made the tutorials into rust docs. I think tokio does something like this? If we still want to do model this after those docs, we should leave it open

**Comment by flaub** [comment]
All the code snippets in the dev website is now under test using: https://github.com/risc0/risc0/tree/main/website/doc-test/main

**Comment by SchmErik** [comment]
thanks for the info! closing
