### ISSUE TITLE
go risc0 example

### ISSUE THREAD

**Issue by GopherJ** [risc0/risc0#1140]

**Comment by GopherJ** [comment]
seems go compiler doesn't support riscv32 ISA

**Comment by pepyakin** [comment]
You may have better luck with tinygo, although it does have its limitations.

**Comment by flaub** [comment]
We don't yet have support for go. We've experimented with adding support for tinygo, and we had some success but nothing released just yet.

**Comment by jax-cn** [comment]
## Context: Compiling and Running `fib_go.go` with `risc0/tinygo` Result Error

### What happens
I successfully compiled an ELF binary using `risc0/tinygo` with the command `tinygo build -target zkvm fib_go.go`. However, when attempting to run the resulting binary with `r0vm --elf fib_go`, I encountered the following runtime error:
```
thread 'main' panicked at risc0/r0vm/src/lib.rs:129:20:
called Result::unwrap() on an Err value: address 0x00000001 is an invalid guest address
```
This suggests that the ELF binary does not conform to the expected ELF specification required by `zkvm` for guest programs.

### Prior Discussions
I've reviewed the previously closed issue and noted that there was mention of partial success with `tinygo`. However, it seems that there have been no recent updates to the `tinygo` project, which leads me to suspect that there might have been changes to `zkvm` that affect the compatibility of the binaries produced by `tinygo`.

### Questions and Assistance Request
Would it be possible for you to share the results from your experimentation with `tinygo`? Any insights or progress made could be incredibly helpful for others encountering similar issues.

Additionally, I wanted to inquire if there have been any recent changes to the `zkvm` that might require updates to the guest program specifications or the way `tinygo` compiles binaries for `zkvm`.

### Apology for Off-Topic Issue Post
I apologize for raising this issue in the `risc0` project tracker. I've noticed that the `tinygo` project does not have issues enabled, which leaves me with no direct avenue to raise this concern there. I hope you understand the necessity of reaching out through this channel and appreciate any guidance you can provide.
