### ISSUE TITLE
Lack of SSH-identity causes failure to clone

### ISSUE THREAD

**Issue by KaiserKarel** [risc0/risc0#1145]
Calling cargo risczero new leads to the following error. 

```
thread 'main' panicked at risc0/cargo-risczero/src/commands/new.rs:195:10:
Failed to generate project: Please check if the Git user / repository exists.

Caused by:
    authentication required but no callback set; class=Ssh (23); code=Auth (-16)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

My guestimate is that my ssh-config isn't being honored.

https://github.com/risc0/risc0/blob/a7444579f8f4b90c28c656db4a19e648f8b4f414/risc0/cargo-risczero/src/commands/new.rs#L186C1-L187C1

**Comment by flaub** [comment]
I think this is resolved with 1.0, we no longer use git to clone the template.
