### ISSUE TITLE
Download(risc0-circuit-recursion-70bfa09004bfe688/out/recursion_zkr.zip: (verification: unverified)

### ISSUE THREAD

**Issue by GopherJ** [risc0/risc0#1163]

**Comment by rahulghangas** [comment]
Seeing the same

**Comment by ayg2002** [comment]
didn't work on my side as well

**Comment by SchmErik** [comment]
> this happened while running `cargo check` but it's fine in `cargo build`

Where are you running this on? The starter template? the risc0 repo?

**Comment by flaub** [comment]
I think we have a fix for this that will be ready in the next release: https://github.com/risc0/risc0/pull/1184

**Comment by flaub** [comment]
A better fix is here: https://github.com/risc0/risc0/pull/1367
