### ISSUE TITLE
Prover disk exhaustion

### ISSUE THREAD

**Issue by zeegomo** [risc0/risc0#1169]
When setting the segment limit to 14, the prover will use up more than 100GB of disk space before crashing.
I would expect it to consume roughly twice as much space as setting the limit to 15 or return with an error if that's not possible for some reason. Note that `MIN_PO_2` is set to 6 in code.

### Steps to reproduce on MacOS 13.5
* checkout hello-world example from v0.19.1
* set the segment limit to 2^14 with 
```let env = ExecutorEnv::builder()
        // Send a & b to the guest
        .write(&a)
        .unwrap()
        .write(&b)
        .unwrap()
        .segment_limit_po2(14)
        .build()
        .unwrap();
```

* run prover

**Comment by SchmErik** [comment]
Thanks for filing this! Notes for myself: this is a corner case in the cycle accounting. The executor clears the segments/cycles but repopulates with several page load's that increase the cycle limits. In other cases, the cycles that have been incurred before the executor's step function can be split over multiple segments but when segment po2 =14, we can get into a situation where the cycle count of initialization of the segment + first instruction can be too large and cannot be split. I need to write an extra conditional to account for this corner case and bail.
