### ISSUE TITLE
cuda.rs panic when run cuda benchmark

### ISSUE THREAD

**Issue by ironGYII** [risc0/risc0#1193]
Hallo, When I run cargo run --release -F cuda --example loop, I encounter a panic exception:
```
risc0-zkvm-methods-std:     Finished release [optimized] target(s) in 0.16s
   Compiling risc0-zkvm v0.20.0-alpha.1 (/root/env/gpu/risc0/risc0/zkvm)
    Finished release [optimized] target(s) in 1m 18s
     Running `target/release/examples/loop`
|     Cycles |   Duration |        RAM |       Seal |      Speed |
thread 'main' panicked at /root/env/gpu/risc0/risc0/zkp/src/hal/cuda.rs:434:63:
called `Result::unwrap()` on an `Err` value: UnknownError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at risc0/zkvm/examples/loop.rs:169:5:
```
Based on the file path, the error seems to occur in cuda.rs, but I can confirm that my CUDA installation is not the problem because I ran CUDA test cases and received correct results. I am currently using the Ubuntu operating system with an RTX 3060 GPU and CUDA 12.2 installed:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

**Comment by ironGYII** [comment]
Use Tag v0.19.0 can resolve this issue. 
Thank you so much to the developer who helped me on Discord. I really appreciate it.

**Comment by Vap0RSh4wN** [comment]
> ironGYII

hi, does tag 0.19.0 mean the version of risc0?
