### ISSUE TITLE
`store_region_to_guest_memory` does not generate a `MemorySet` trace event

### ISSUE THREAD

**Issue by weikengchen** [risc0/risc0#1194]
When I am testing our profiler (https://github.com/l2iterative/profiler0), I noticed the following result about syscalls from the profiler. The profiler is supposed to capture memory operations and attribute it to the preceding instruction. 

**Problem:** It does not work for some syscalls.

**Cause:** Functions that write memory using `store_region_to_guest_memory` do not trigger a `MemorySet` trace event.

------------------------------

Observation as follows.

Syscalls for SHA:
```
············ Cycle: 46660 => 47975: ecall at 0x204310 takes 1315 cycles
············ Cycle: 51139 => 52454: ecall at 0x204310 takes 1315 cycles
```

Syscalls for read:
```
············ Cycle: 29078 => 30243: ecall at 0x2044fc takes 1165 cycles
············ Cycle: 30327 => 31728: ecall at 0x2044fc takes 1401 cycles
```

But, syscalls for bigint:
```
········ Cycle: 57940 => 59044: ecall at 0x204364 that accesses 0x1ff430, 0x1ff434, 0x1ff438, 0x1ff43c, ..., 0x1ff44c takes 1104 cycles
```

The reason that this profiler does not work for the other syscalls is because:
- syscall SOFTWARE (https://github.com/risc0/risc0/blob/main/risc0/zkvm/src/host/server/exec/executor.rs#L755) uses `monitor.store_region_to_guest_memory`
- Same for syscall SHA (https://github.com/risc0/risc0/blob/main/risc0/zkvm/src/host/server/exec/executor.rs#L649)
- But, bigint uses `store_u32_to_guest_memory` (https://github.com/risc0/risc0/blob/main/risc0/zkvm/src/host/server/exec/executor.rs#L704)

The `store_region_to_guest_memory` calls `store_region`, which calls `raw_store_u8` that calls `store_bytes`. Although `raw_store_u8` remembers to load the page (through `load_u8`) and mark the page as dirty (which is important), it just does not create a trace event. 
```rust
    fn store_bytes(&mut self, addr: u32, bytes: &[u8]) -> Result<()> {
        let info = &self.image.info;
        let page_idx = self.get_page_index(addr)?;
        let offset = addr % info.page_size;
        self.pages[page_idx as usize]
            .get_or_insert_with(|| Page {
                buf: self.image.load_page(page_idx),
            })
            .store_bytes(offset, bytes);
        Ok(())
    }

    fn raw_store_u8(&mut self, addr: u32, data: u8) -> Result<()> {
        // tracing::trace!("raw_store_u8: 0x{addr:08x}");
        let old = self.load_u8(addr)?;
        self.pending_actions.push(Action::StoreU8(addr, old));
        self.store_bytes(addr, &[data])?;
        self.mark_page(addr);
        Ok(())
    }

    pub fn store_region(&mut self, addr: u32, slice: &[u8]) -> Result<()> {
        // tracing::trace!("store_region: 0x{addr:08x}");
        slice
            .iter()
            .enumerate()
            .try_for_each(|(i, x)| self.raw_store_u8(addr + i as u32, *x))?;
        Ok(())
    }

    pub fn store_region_to_guest_memory(&mut self, addr: u32, slice: &[u8]) -> Result<()> {
        Self::check_guest_addr_range(addr, addr + u32::try_from(slice.len())?)?;
        self.store_region(addr, slice)
    }
```

The present question is whether this is intentional, and if not, do you want a PR?

**Comment by flaub** [comment]
For a large region, this would generate a ton of byte events, when really we just need a single 'region' event.

**Comment by weikengchen** [comment]
I am in favor of a single region event, as it would also be easier for the debugger/profiler to manage. This would require a breaking change to the API.
