### ISSUE TITLE
[BUG] temp segment file storage not deleted after use

### ISSUE THREAD

**Issue by austinabell** [risc0/risc0#1223]
## Bug Report

Currently, when a temp directory is initialized (as the default) for file storage, [`into_path`](https://docs.rs/tempfile/latest/tempfile/struct.TempDir.html#method.into_path) is immediately called:

https://github.com/risc0/risc0/blob/cee4239273e827e9d0a9b12714fb7c4c3175d231/risc0/zkvm/src/host/server/exec/executor.rs#L234

Which bypasses the deletion of the file on `Drop`, and this can get quite leaky with storage space if running a lot of workflows.

A couple options to have these be deleted is:
1. Handle ownership of the tempdir through having the segment path location stored as an enum (or sth like this)
2. Add a new type, which would have a `Drop` impl to delete the file, use this as the default
    - Can use https://docs.rs/tempfile/latest/tempfile/fn.tempfile_in.html as an alternative
    - Allows files to be incrementally deleted as the segments are proven
    - This solution, in the case of a temp dir creation, would not remove the directory itself at the end of execution

## Steps to Reproduce
1. 
2.
3.

## Your Environment
- risc0-zkvm version: 0.20.0-alpha (main)
- Rust version: 1.73
- Platform/OS: mac

**Comment by weikengchen** [comment]
Can I say that the most elegant way is to preserve the tempdir, and call `close` upon finishing? 

https://docs.rs/tempfile/latest/tempfile/struct.TempDir.html#method.close

**Comment by austinabell** [comment]
> Can I say that the most elegant way is to preserve the tempdir, and call `close` upon finishing?
> 
> [docs.rs/tempfile/latest/tempfile/struct.TempDir.html#method.close](https://docs.rs/tempfile/latest/tempfile/struct.TempDir.html#method.close)

Good point, it could be useful to handle any error to be able to warn if the temp dir was not deleted, rather than the error being ignored on drop. 👍

**Comment by SchmErik** [comment]
Fixed by: https://github.com/risc0/risc0/pull/1421
