### ISSUE TITLE
[Feature] Improve faulted session error message

### ISSUE THREAD

**Issue by weikengchen** [risc0/risc0#1229]
## Feature

I was encountering the `faulted session` error. Eventually, I found that there are two bugs in my code, but the problem is that RISC Zero toolkit never provided the actual error message---I have to eventually use the [gdb0](https://github.com/l2iterative/gdb0) tool to figure out where it starts to go wrong, and why.

So, I am requesting improved error message for faulted session.

- for 0.19.1, currently, the error message is only "faulted session", without the original error message passed from the rrs library.
- for the `main` branch, the problem is indeed **_very severe_**, because I see completely **_no_** error message from the execution. The output is blank. 

So, I think at the very least, one needs to restore the error message in the current main branch. Ideally, the original error message from the rrs library is exposed.

## Motivation
Easier debugging if some unsafe memory operations cause illegal instructions.

## Implementation
Recommend to use anyhow to send the error message with the original error message from rrs. More fundamentally, the `main` branch should be able to deliver at least the "faulted session" error instead of leaving the output blank.

-----

For reference, the underlying errors that I eventually undercover are alignment errors, from two places.

**Issue 1.** If I use `include_bytes!` but intend to rephrase the bytes into a data structure, as in the example below.
```rust
static BSK_BYTES: &[u8] = include_bytes!("../../../bsk");
let bsk = black_box(unsafe {
    std::mem::transmute::<&u8, &[GgswCiphertext; 16]>(&BSK_BYTES[0])
});
```
 
There is a possibility that it would trigger `faulted session` because the `BSK_BYTES` could be just aligned to byte. But I actually need them to align to u32. This is solved by the `include_bytes_aligned` macro.

**Issue 2.** I used transmute to cast a pointer to u8 into a pointer to u32, in order to copy data faster by copying 32-bit at a time. However, if the u8 is not at aligned to u32, this would also failed.

```rust
unsafe {
    let len = $msg.len();
    core::ptr::copy(
        core::mem::transmute::<*const u8, *const u32>($msg.as_ptr()),
        TRACE_MSG_CHANNEL.as_mut_ptr(),
        (len + 3) / 4,
    );
}
```

This is basically due to my use of `transmute` without taking care of alignment. I fixed my code (https://github.com/l2iterative/profiler0/commit/8f4aec90cb9126b911b16a61023deb5209fe468c) by not doing the casting.

**Comment by SchmErik** [comment]
So we're removing the proof of fault from the zkvm for now and do this as a part of future circuits. so https://github.com/risc0/risc0/pull/1317 reverts to the old behavior and give you the error message from the rrs library. Closing
