### ISSUE TITLE
[BUG] Pull the template may require git pull the entire risc0 and its submodules

### ISSUE THREAD

**Issue by weikengchen** [risc0/risc0#1271]
## Bug Report

So, when the developers' network conditions are mediocre (such as, in a hotel), using `cargo-risczero` to start a project from the template may fail due to network errors.
https://github.com/risc0/risc0/blob/main/risc0/cargo-risczero/src/commands/new.rs

This may appear unexpected because the template is a very small folder. 

The problem rests on the fact that `cargo-generate`, which `cargo-risczero` relies on, when being told to use a "subdirectory" of a GitHub repo, 
- it pulls the entire repo, here risc0/risc0, as well as its submodules
- it gets the subdirectory

As shown here: https://github.com/cargo-generate/cargo-generate/blob/main/src/lib.rs#L214C3-L214C3

This is not ideal for two reasons.
- the risc0 repo is getting big, as the recursion programs' ZIP is not small
- Bonsai smart contract part has a few dependencies that lead to submodule usage

## Solution

Move the template into a separate repo, with the side effect that we need to be careful about version management. This is less of a concern because by default, "use_git_branch" is optional and not used.

**Comment by flaub** [comment]
I'd like to keep the template in the same repository, for testing/CI reasons. But we can fix the generator to avoid using any git references by default.

**Comment by SchmErik** [comment]
here's an approach: https://github.com/cargo-generate/cargo-generate/pull/1112

**Comment by SchmErik** [comment]
> But we can fix the generator to avoid using any git references by default.

Ok, so I tried the --no-git option for `cargo risczero new`. Following around in the cargo generate code, it looks like git is basically hard-coded. Even if you say that you're not going to use git, it'll fall back to using git so I think the fastest way is to ask upstream to allow skipping submodules. It took down the template generation from 15-30 seconds to about 9 seconds

**Comment by weikengchen** [comment]
This seems to be due to "--no-git" is to not initialize git "/// Disable init'ing a git repo in the dest project" rather than not to pull the template from the git.

**Comment by weikengchen** [comment]
For the record, this still isn't most elegant, as it would try to get all the rest of risc0 repo. This luckily does not include the LFS file (since, cargo-generate does not support it), but still wondering if there is a more clever way.

One way is to access risc0/risc0 through git without cloning. I.e., it goes to the template folder and starts downloading files in it one by one. Not sure if this can be done very elegantly.

**Comment by flaub** [comment]
I'd like to explore ditching `cargo-generate` and just using string templating to generate the project files. I don't know that we need the ability to pull down a template from a different version. We could say that if you want a different version of the project generator, then just install a different version of `cargo-risczero`.

**Comment by flaub** [comment]
We finished this just before 1.0 landed
