### ISSUE TITLE
[BUG] rust toolchain: HashMap and HashSet should use sys_rand

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#1275]
## Bug Report
As of this writing, our rust toolchain does not support using random numbers to prevent a DOS attack on the `alloc::collection::Hashmap` or `HashSet`

## Steps to Reproduce
In the guest, initialize a hashmap and insert data in such a way to cause a hash collision. Since hashmap and hashset do not have any entropy, this collision will be deterministic. This means that running this guest program repeatedly will result in the same collision.

## Expected behavior
To avoid this DOS attack, it's commonly expected that `HashMap` and `HashSet` use random keys during initialization and repeatedly invoking the guest will not result in collisions.

## Your Environment
- risc0-zkvm version: this problem exists solely on the risc0 rust toolchain.
- Rust version: risc0 toolchain version 1.69
- Platform/OS: macOS but this is OS-agnostic.

**Comment by SchmErik** [comment]
I'm planning on picking this up after the new year

**Comment by weikengchen** [comment]
The key is about how to get this work: https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#3126

**Comment by weikengchen** [comment]
This is related to https://github.com/rust-lang/rust/pull/117958/files#diff-e014b9a8f5d1cc2cb5074f95f527ae8ef1d47596a64bb32768470304fb1bfa24R48

```
#[path = "../unsupported/common.rs"]
#[deny(unsafe_op_in_unsafe_fn)]
mod common;
pub use common::*;
```

Currently, it uses functions from `common.rs` of `unsupported`, which gives:
```rust
pub fn hashmap_random_keys() -> (u64, u64) {
    (1, 2)
}
```

So what you need to do is to:
- not use unsupported/common.rs. Better just copy the code to zkvm.
- implement `hashmap_random_keys` using `sys_rand`, initialize a u32 vector `a: [u32;4]` of size 4, `sys_rand` it, and:
```rust
pub fn hashmap_random_keys() -> (u64, u64) {
    let mut a = [0u32; 4];
    abi::sys_rand::(&mut a, 4);
    ((a[0] as u64 << 32) + a[1] as u64,  (a[2] as u64 << 32) + a[3] as u64)
}
```

**Comment by SchmErik** [comment]
@weikengchen Thanks! yup, this is basically what I was going to do. I'll put you down as a co-author in the commit

**Comment by weikengchen** [comment]
This appears to have been done.

https://github.com/rust-lang/rust/pull/117958/files#diff-e6a1be93a16f21064d9d2d025e9b5df039e2470419337fe74a36fa9bdaa7ec6fR90

**Comment by SchmErik** [comment]
I'd like to leave this open until we publish the 1.75 toolchain

**Comment by SchmErik** [comment]
A version of the toolchain containing this can now be installed with the following command: `cargo risczero install --version v2024-02-08.1`
