### ISSUE TITLE
Provide prebuilt binaries for arm64 linux.

### ISSUE THREAD

**Issue by pepyakin** [risc0/risc0#1286]
AFAICT, risc0 targets to support first class DX on linux and macOS.

To quote [this](https://github.com/risc0/risc0/blob/486940740221fef76047b37daad0bb059bda01b8/risc0/cargo-risczero/README.md?plain=1#L38C1-L42)

> Note that the following pre-built host targets are available:
>
>
> * `aarch64-apple-darwin`
> * `x86_64-apple-darwin`
> * `x86_64-unknown-linux-gnu`

however, binaries for `aarch64-unknown-linux-gnu` are not provided. It's not only a problem for linux but it's also a problem for macOS users since docker would run under `aarch64`.

IMO, those lines should work without compiling under docker running under macOS on apple silicon.

```
cargo binstall risc0
cargo risczero install
```

**Comment by flaub** [comment]
We currently don't have any arm64 linux machines in our CI, so that would be required for us to do that here. Perhaps in the future this will make sense.

**Comment by JuaniRios** [comment]
Need this also
