### ISSUE TITLE
[BUG] `cargo binstall cargo-risczero` fails because of protobuf-src error

### ISSUE THREAD

**Issue by ustas-eth** [risc0/risc0#1294]
## Bug Report
The protobuf-src v1.1.0+21.5 dependency throws the following error during the installation of cargo-risczero:

```logs
error: failed to run custom build command for `protobuf-src v1.1.0+21.5`

Caused by:
  process didn't exit successfully: `C:\Temp\cargo-installWmoTbS\release\build\protobuf-src-0fa2cef98d6aabec\build-script-build` (exit code: 101)
  --- stdout
  running: "sh" "-c" "exec \"$0\" \"$@\"" "D:\\cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\protobuf-src-1.1.0+21.5\\protobuf\\configure" "--prefix=C:\\Temp\\cargo-installWmoTbS\\release\\build\\protobuf-src-8a01327fdea19198\\out\\install" "--disable-shared" "--enable-static" "--disable-maintainer-mode"

  --- stderr
  configure: error: cannot find required auxiliary files: ltmain.sh ar-lib compile missing install-sh config.guess config.sub
  thread 'main' panicked at D:\cargo\registry\src\index.crates.io-6f17d22bba15001f\autotools-0.2.6\src\lib.rs:781:5:

  command did not execute successfully, got: exit code: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Steps to Reproduce
1. Run `cargo binstall cargo-risczero`

## Your Environment
- risc0-zkvm version: current
- Rust version: 1.75.0 (82e1608df 2023-12-21)
- Platform/OS: Windows 10, 19044.3086

## Additional context
These links might be useful:
- https://github.com/risingwavelabs/risingwave/issues/9387
- https://github.com/googleforgames/quilkin/issues/814

**Comment by flaub** [comment]
What version of `risc0-zkvm` are you trying to use?

**Comment by flaub** [comment]
Note that we don't have support for pre-built binaries on Windows, and so that means `cargo binstall` will try to build from source. In which case you'll need to follow these instructions:

https://github.com/protocolbuffers/protobuf/blob/main/src/README.md

Note also that we don't support Windows at this time (we don't test it in our CI), but it might work :)

**Comment by ustas-eth** [comment]
> What version of `risc0-zkvm` are you trying to use?

I assume this is the version: cargo-risczero v0.19.1

It seems like the build on Windows should work if only there weren't the issue. And I don't think protobuf is OS specific 😅 Maybe changing the package version will help.
I hope you'll add it to the CI in the future for those who are stuck with Windows :)
I'm a participant of zkEVM Bootcamp by Encode. I was just trying to complete our homework after the presentation by RISC Zero, so I'm not very familiar with the project yet.
Anyway, I'll try to use WSL, though I'm afraid of the performance.

**Comment by ustas-eth** [comment]
@flaub WSL works fine!
