### ISSUE TITLE
Remove slice_io APIs

### ISSUE THREAD

**Issue by austinabell** [risc0/risc0#1316]
Tracking issue to either document, find a valid pattern that can't be solved with posix based IO, or remove the slice_io APIs. As suggested by @flaub, it might make the most sense to just remove these.

The only example that uses these APIs is the waldo example 
https://github.com/risc0/risc0/blob/d2502d46270a1fe0f0b53059ce8de1fc662539c7/examples/waldo/src/bin/prove.rs#L121

and it seems like a reasonable use case, so probably best to start there to make sure that pattern can be handled well without it before migrating away from the slice_io APIs (if that decision is made).

Links to some of the APIs:
https://github.com/risc0/risc0/blob/d2502d46270a1fe0f0b53059ce8de1fc662539c7/risc0/zkvm/src/host/client/env.rs#L306
https://github.com/risc0/risc0/blob/d2502d46270a1fe0f0b53059ce8de1fc662539c7/risc0/zkvm/src/host/client/env.rs#L315
https://github.com/risc0/risc0/blob/d2502d46270a1fe0f0b53059ce8de1fc662539c7/risc0/zkvm/src/guest/env.rs#L298
https://github.com/risc0/risc0/blob/d2502d46270a1fe0f0b53059ce8de1fc662539c7/risc0/zkvm/src/host/client/slice_io.rs#L28

**Comment by flaub** [comment]
Since this isn't a blocking issue, I'm going to close for now. Perhaps we can reopen in the future, but I suspect the API will change a bunch so this becomes obsolete.
