### ISSUE TITLE
Broken links to docs in articles on risczero.com

### ISSUE THREAD

**Issue by pdg744** [risc0/risc0#1328]
The links to the crate docs in the [continuations article](https://www.risczero.com/news/continuations) are broken. 
Not sure whether this problem applies to other blog posts as well.

Do we still have a link checker active somewhere?

**Comment by flaub** [comment]
Can you list which links are broken?

**Comment by pdg744** [comment]
All of these are broken:

<img width="803" alt="image" src="https://github.com/risc0/risc0/assets/15272444/19fd4af9-6bd2-4840-97fd-9b2c5c02b647">
