### ISSUE TITLE
How to get the riscv32im-risc0-zkvm-elf toolchain

### ISSUE THREAD

**Issue by bishopcheckmate** [risc0/risc0#1330]
Hey, I have been experimenting with some current usages of unsafe in the code and I tried running `cargo clippy -- -W clippy::all -W warnings` to check how much surface does it affect. I've managed to install the required foundry tools and tried `cargo risc0 install` but it seems I'm still missing this toolchain. How to properly set this up?

**Comment by flaub** [comment]
Clippy is not yet included in our toolchain for the rv32im target. We hope to get this included in an upcoming release.

**Comment by bishopcheckmate** [comment]
oh thanks, so the issue is clippy command, not the toolchain itself. I haven't expect that

**Comment by bishopcheckmate** [comment]
out of curiosity, what is needed to have it?

**Comment by flaub** [comment]
https://github.com/risc0/risc0/issues/997
