### ISSUE TITLE
Write ECALL specification

### ISSUE THREAD

**Issue by carterbrett** [risc0/risc0#1333]
risc zero's zkVM implements the RV32IM instruction set with several ecalls. These ecalls are specific to the RISC Zero zkVM and it's behavior (including failure cases) should be documented.

**Comment by pdg744** [comment]
There are some comments on this topic in the docs here: https://dev.risczero.com/api/zkvm/developer-guide/zkvm-specification

**Comment by flaub** [comment]
This will be resolved by moving to the Linux ABI
