### ISSUE TITLE
[BUG] Do we need LFS for recursion_zkr.zip?

### ISSUE THREAD

**Issue by weikengchen** [risc0/risc0#1344]
## Bug Report

There have been a few issues in this repository about LFS about recursion_zkr.zip. In December, the situation is as follows.

> This file is over 50MB currently and contains firmware code that is executed by the recursion circuit. I haven't yet found a way to make this code available as normal source since GitHub has a limit on the size that files can be that's checked in. So right now it's using LFS and then the build script downloads it at build time. I realize this is less than ideal and I'm looking for alternatives.

https://github.com/risc0/risc0/issues/1142
https://github.com/risc0/risc0/issues/1180

However, the file nowadays is no longer 50MB. It is 24.3MB.
https://github.com/risc0/risc0/blob/main/risc0/circuit/recursion/src/recursion_zkr.zip

Should we revisit the decision of incorporating the LFS?

--- btw, if we encounter the upload limit about crates.io, about 8 years ago crates.rs has decided to handle large-file requests in a case-by-case manner (https://github.com/rust-lang/crates.io/issues/40#issuecomment-157919165). It remains, however, a problem whether crates.io could handle such traffic and whether it is definitely a bad idea to include it in the uploaded crate.

**Comment by flaub** [comment]
This issue is only relevant for users that want to build from source. If users use the binary release, then this can be avoided. I don't know of any good alternatives at this time.

**Comment by flaub** [comment]
For using crates, the build script should download the ZKR from an S3 bucket, so crates from crates.io should work. If this isn't working as intended we can open a ticket for that issue.

**Comment by weikengchen** [comment]
Actually that is what I want to follow up next. So, **for people who build from sources.**

Would it help to let the build script ignore a dummy LFS?
https://github.com/risc0/risc0/blob/main/risc0/circuit/recursion/build.rs#L54C12-L54C12

Currently, the build script would copy-paste the zip file if it **_exists_**.

```rust
if std::fs::metadata(&src_path).is_ok() {
    let tgt_path = out_dir.join(FILENAME);
    std::fs::copy(&src_path, &tgt_path).unwrap();
}
```

But the one that exists could be the 133-byte LFS metadata file. 
```
version https://git-lfs.github.com/spec/v1
oid sha256:ae5736a42189aec2f04936c3aee4b5441e48b26b4fa1fae28657cf50cdf3cae4
size 25527822
```

This would lead to an error:
```
thread '<unnamed>' panicked at /Users/cusgadmin/.cargo/git/checkouts/risc0-b4649977e2e81438/341a014/risc0/circuit/recursion/src/zkr.rs:29:71:
called `Result::unwrap()` on an `Err` value: InvalidArchive("Could not find central directory end")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/cusgadmin/RustroverProjects/r0prover-python/test/test.py", line 33, in <module>
    receipt_1_lifted = l2_r0prover.lift_segment_receipt(receipt_1)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: InvalidArchive("Could not find central directory end")
```

It would be great if the build script, after seeing a file there that is definitely not the actual zip file (such as hash mismatch), would instead download it from the S3 bucket.

How do you think?

**Comment by weikengchen** [comment]
I will follow up on this with a PR.
