### ISSUE TITLE
Enforced prove, lift, join benchmarks

### ISSUE THREAD

**Issue by carterbrett** [risc0/risc0#1350]
These benchmarks are important drivers for cost and we need to make sure we're only introducing performance regressions knowingly. Perhaps only privileged github org users can override. This is particularly important to prevent cost/performance regressions in Bonsai.

**Comment by flaub** [comment]
Let's chat about this, we already have the start of it, and we had something to check for this, but we ran into lots of issues with it.

**Comment by flaub** [comment]
Depends on #1369 
Depends on devops#90
