### ISSUE TITLE
[Feature] zkVM: use register `a7` instead of `t0` to identify ecalls

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#1353]
## Feature
For zkVM 1.0, we want to implement the linux syscall ABI in the zkVM. This means that we want to use `a7` as the register that contains information that identifies which ecall is being requested to run.

## Motivation
We want to implement this so that we can borrow this convention from linux. This means that when one compiles a file that's meant to run as a linux userspace application on a risc-v processor, the system calls can be compatible. In practice, we will likely not implement most of the syscalls in the host because not all linux syscalls have a parallel to the zkVM. One out come of this adoption will be the assembly code for `sys_read` will be identical to the ones implemented in the zkVM.

## Implementation

- [ ] change the zkVM executor to use a7 instead of t0
- [ ] change the RV32IM circuit to use a7 instead of t0

**Comment by flaub** [comment]
This didn't make it for 1.0
