### ISSUE TITLE
[Feature] Make CUDA contexts fork-safe in Linux

### ISSUE THREAD

**Issue by weikengchen** [risc0/risc0#1370]
## Feature
This is probably an issue that subjects to immediate closure as it is not an intended use of RISC Zero. 

The idea is that, in Linux.

If the RISC Zero prover is being executed in an environment where the process could be forked (in the sense of Linux), and the fork happens after the CUDA Context is created (which is "CONTEXT" under `lazy_static`, so it gets created when it is first being referenced, usually when the first CUDA HAL is created), the child processes are going to suffer from segment faults because it "steals" the contexts from the parents, but CUDA doesn't allow different processes sharing each other's contexts.

CONTEXT is here:
https://github.com/risc0/risc0/blob/main/risc0/zkp/src/hal/cuda.rs#L49

The fix seems to be simple: do the following for Linux: save a PID when the context is created, when acquiring the CONTEXT, check if the PID is the same as the one that creates it, if not, create a new context and save it for this new thread.

## Motivation
This is more or less related to packaging the RISC Zero prover into a Python module and getting used by Ray (which uses fork). It is not a problem today, and it is doing okay when getting used by Dask (which uses spawn).

## Implementation
See above. But, to be honest, Rust has made it clear that forking causes undefined behaviors. It is generally okay and likely not going to affect security, for example, Rust's implementation on thread_rng makes sure that children do not inherit parents' randomness, and RISC Zero has been using thread_rng rather than creating a long-lasting global RNG.

**Comment by flaub** [comment]
This is yet another reason why integrating in-process at the library level can be difficult. The architecture we are headed for is to use an out-of-process model to avoid these kinds of issues.

**Comment by weikengchen** [comment]
I think I am going to close this issue. It appears that CUDA just cannot be fork-safe.
