### ISSUE TITLE
[BUG] Reproducible builds fail on macOS (execstack)

### ISSUE THREAD

**Issue by flaub** [risc0/risc0#1385]
## Bug Report
`cargo risczero build` fails on macOS 14.3 with the following:
```
 => ERROR [build 4/5] RUN cargo +risc0 fetch --locked --target riscv32im-risc0-zkvm-elf --manifest-path risc0/zkvm/methods/guest/Cargo.toml                                                                   0.8s
------
 > [build 4/5] RUN cargo +risc0 fetch --locked --target riscv32im-risc0-zkvm-elf --manifest-path risc0/zkvm/methods/guest/Cargo.toml:
0.248     Updating crates.io index
0.823 error: process didn't exit successfully: `/root/.rustup/toolchains/risc0/bin/rustc -vV` (exit status: 127)
0.823 --- stderr
0.823 /root/.rustup/toolchains/risc0/bin/rustc: error while loading shared libraries: libLLVM-15-rust-1.69.0-nightly.so: cannot enable executable stack as shared object requires: Invalid argument
0.823
```

## Steps to Reproduce
1. `cargo risczero build --manifest-path risc0/zkvm/methods/guest/Cargo.toml`

Alternatively:
```
cargo test -F docker -p risc0-build
```

## Expected behavior
Successful execution of build or test.

## Your Environment
- risc0-zkvm version: `0.21.0-alpha.1`
- Rust version: `1.73.0`
- Platform/OS: macOS 14.3

**Comment by flaub** [comment]
Related: https://github.com/rust-lang/rust/issues/105783

**Comment by flaub** [comment]
This now seems to work on macOS 14.3.1, closing for now

**Comment by intoverflow** [comment]
Same issue encountered on MacOS 14.3.1 with Docker 25.0.3 and Docker Desktop v4.28.0.

cargo risczero --version gives 0.20.1. rustc --version gives 1.75.0.

Encountered when building Zeth, which is based on zkVM 0.20.1.

**Comment by intoverflow** [comment]
Upgrading to MacOS 14.4 resolved the issue for me.
