### ISSUE TITLE
Error running `cargo` on MacOS with explicit toolchain `channel = 1.73`

### ISSUE THREAD

**Issue by snowmead** [risc0/risc0#1433]
## Bug Report

Running `cargo` commands fail on `1.73-aarch64-apple-darwin` toolchain. 

Error produced:
```
error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the '1.73-aarch64-apple-darwin' toolchain
```

The `toolchain.toml` explicitly sets the rust toolchain version `channel = "1.73"`. Removing this fixes the problem.

## Steps to Reproduce
1. Run any `cargo` command with 1.73-aarch64-apple-darwin toolchain

## Expected behavior

`cargo` command is executed.

## Your Environment
- risc0-zkvm version: cargo-risczero 0.20.1
- Rust version: 1.76.0
- Platform/OS: MacOS

**Comment by SchmErik** [comment]
At this time, we're I can't reproduce this on my end using the current head of the risc0 repo. I'm doing `cargo build -p risc0-zkvm` and it runs without displaying this error

**Comment by snowmead** [comment]
I tried on `main` and `release-0.20`, but no luck. This isn't a blocker necessarily, since I commented out the the `channel = "1.73"`, but thought I should point this out.

**Comment by SchmErik** [comment]
we updated to 1.74 today. Does this still persist on your end?

**Comment by Qgoni** [comment]
I seem to be doing well.
