### ISSUE TITLE
Reproducible build workflow and documentation

### ISSUE THREAD

**Issue by nategraf** [risc0/risc0#1481]
Verifying image IDs by building from source is part of the security model for many zkVM applications. In particular, applications integrating with smart contracts will generally need to provide users with a process by which they can reproduce the image ID from source.

Today we have a feature in `rics0-build` to run the build in Docker, and by doing so make is reproducible. We need to have a workflow that we can provide zkVM app developers, and the app developers can provide the consumers of their code, to run this reproducible build. This workflow should be generic across projects, both using the Foundry template and not, and easy to follow.

**Comment by flaub** [comment]
Isn't this the goal of `cargo risczero build`? I think it's also related to the upcoming `cargo risczero deploy` command.

Related (dup?):

**Comment by nategraf** [comment]
Closing in favor of #1084
