### ISSUE TITLE
[BUG] The 'risc0' toolchain could not be found for x86_64-apple-darwin

### ISSUE THREAD

**Issue by allemanfredi** [risc0/risc0#1485]
## Bug Report
I followed the [steps](https://github.com/risc0/risc0/tree/main/risc0/cargo-risczero#installation) to install `cargo-risczero` (using `--path`)  but when i run `cargo run` within a project created with `cargo risczero new` i get the following error:

```
error: failed to run custom build command for `methods v0.1.0 (/Users/allemanfredi/Desktop/risc0-farcaster/methods)`

Caused by:
  process didn't exit successfully: `/Users/allemanfredi/Desktop/risc0-farcaster/target/debug/build/methods-f5b2d485b209464c/build-script-build` (exit status: 255)
  --- stderr
  The 'risc0' toolchain could not be found.
  To install the risc0 toolchain, use cargo-risczero.
  For example:
    cargo binstall cargo-risczero
    cargo risczero install
warning: build failed, waiting for other jobs to finish...
```

I also tried to run `cargo risczero install` (without --path) but i get this error:
```
Getting release info: https://api.github.com/repos/risc0/rust/releases/latest...
Could not download pre-built toolchain: Release v2024-01-31.1 does not have a prebuilt toolchain for host x86_64-apple-darwin
Error: Download of pre-built toolchain failed

Caused by:
    Release v2024-01-31.1 does not have a prebuilt toolchain for host x86_64-apple-darwin
```
## Steps to Reproduce
1. `cargo install --path risc0/cargo-risczero`
2. `cargo risczero new my_project`
3. `cd my_project`
4. `cargo run`

## Your Environment
- risc0-zkvm version: 0.20.1
- Rust version: rustc 1.76.0 (07dca489a 2024-02-04)
- Platform/OS: macOS 13.6.3

**Comment by SchmErik** [comment]
@allemanfredi hey, so we stopped shipping x86 mac binaries. If you want to build the tool chain for this target please run `cargo risczero build-toolchain`

**Comment by allemanfredi** [comment]
it worked! thanks!
