### ISSUE TITLE
[BUG] not able to install on x86_64-apple-darwin macOS

### ISSUE THREAD

**Issue by chowdhury-bc** [risc0/risc0#1507]
## Bug Report

command : cargo risczero install

Getting release info: https://api.github.com/repos/risc0/rust/releases/latest...
Could not download pre-built toolchain: Release v2024-01-31.1 does not have a prebuilt toolchain for host x86_64-apple-darwin
Error: Download of pre-built toolchain failed

Caused by:
    Release v2024-01-31.1 does not have a prebuilt toolchain for host x86_64-apple-darwin

## Steps to Reproduce
1.
2.
3.

## Your Environment
- risc0-zkvm version:
- Rust version: 1.76
- Platform/OS: x86_64-apple-darwin

**Comment by flaub** [comment]
Seems to be a duplicate of #1485

**Comment by SchmErik** [comment]
@chowdhury-bc you need to run cargo risczero build-toolchain instead of cargo risczero install. I've updated the docs to reflect this: #1512
