### ISSUE TITLE
[Feature] guest support for secp256k1

### ISSUE THREAD

**Issue by pdg744** [risc0/risc0#1509]
## Feature
Would be nice to be able to run the crate for secp256k1 in the guest

## Motivation
requested [here](https://github.com/risc0/risc0/discussions/1292). 
secp256k1 is used on bitcoin

## Implementation
Unclear why this crate doesn't work

**Comment by flaub** [comment]
This crate is patched here: https://github.com/risc0/RustCrypto-elliptic-curves/tree/risczero

**Comment by flaub** [comment]
See: https://dev.risczero.com/api/zkvm/acceleration
