### ISSUE TITLE
[Feature] CI: remove -p argument from `cargo clippy -p risc0-zkvm` for wider clippy coverage

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#1533]
## Feature
We should drop the `-p risc0-zkvm` from the clippy command in main.yml. -p seems to limit clippy coverage to risc0-zkvm only and removing this flag results in clippy warnings in risc0-zkp. 

## Motivation
We want to make sure we're running clippy on all of the crates

## Implementation
1. Wait until Frank finishes the parallel witgen work because it touches files that clippy complains about.
2. Drop the -p risc0-zkvm flag
3. Fix any clippy warnings that appear.

**Comment by Cardosaum** [comment]
Closed by #1706
