### ISSUE TITLE
[BUG] Right-hand side of navbar isn't viewable on mobile

### ISSUE THREAD

**Issue by pdg744** [risc0/risc0#1541]
## Bug Report
On safari on iphone, I can't figure out how to change from v0.20 to other versions of the docs, and I can't find the links that are listed under `community`. 

## Steps to Reproduce
1. Navigate to dev.risczero.com on an iphone.

## Expected behavior
The entire navbar would be visible

**Comment by flaub** [comment]
This is hidden, but I think it's possible:

1. click the menu/hamburger icon in the upper left corner
2. click "<- Back to main menu"
3. select the version you'd like (including "Next") from the "Versions" drop down
