### ISSUE TITLE
[Documentation] Write a documentation on how to use composition to split up large programs

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#1609]
## User's Objective
User wants to run long-running zkVM programs.

## User's Obstacle
User hits cycle limit on bonsai. Existing docs do not outline how to get around this.

## User's Request
The improvement would be to add a section on how to break down very large program executions using composition.

**Comment by flaub** [comment]
I don't think composition can be used for this purpose. The overall amount of work is the same, and if there is a user quota, this won't help AFAIK. Perhaps with the use of pause/resume, you could spread the work out among multiple users.

**Comment by pdg744** [comment]
@SchmErik @flaub should we close this?

**Comment by SchmErik** [comment]
I think we can close this. This sounds better for a pause/resume documentation. Closing for now, feel free to reopen if you have other thoughts
