### ISSUE TITLE
clarify docs for mac x86 users

### ISSUE THREAD

**Issue by pdg744** [risc0/risc0#1641]
During the installation process for `x86_64-apple-darwin` users end up being presented with the fact that `cargo binstall cargo-risczero` currently does not have prebuilt binaries for this architecture. 

Users in this architecture should instead run `cargo risczero build-toolchain`, i.e. build the toolchain from scratch. This is different from what we mention in [`cargo-risczero`](https://crates.io/crates/cargo-risczero)'s documentation, where we say we do provide prebuilt binaries. 

We should be consistent across our documentation pages.

**Comment by pdg744** [comment]
apologies if some of that is incoherent -- I was taking notes based on oral comments.

**Comment by flaub** [comment]
We just need to remove this line:
https://github.com/risc0/risc0/blob/main/risc0/cargo-risczero/README.md?plain=1#L41

**Comment by flaub** [comment]
I think this has been resolved, but please re-open if not.
