### ISSUE TITLE
[BUG] Crate validation report page is broken

### ISSUE THREAD

**Issue by pdg744** [risc0/risc0#1644]
## Bug Report
[This crate validation report](https://risc0.github.io/ghpages/dev/crate-validation/index.html) isn't showing the relevant data. 

<img width="1095" alt="image" src="https://github.com/risc0/risc0/assets/15272444/e92d971c-fa29-4a7b-8078-461b7807dc97">

## Your Environment
- Firefox on Mac

**Comment by nahoc** [comment]
Can probably be closed since we have the new reports/benchmarks:
https://benchmarks.risczero.com/crates-validation
