### ISSUE TITLE
[Documentation] Compact/succinct proof generation

### ISSUE THREAD

**Issue by nazar-pc** [risc0/risc0#1645]
## User's Objective
To generate a compact/succinct proof of execution comparing to current `Receipt` that contains `CompositeReceipt`, which is quite large.

## User's Obstacle
I did some AES computation with zkvm and got receipt, however `bencode` encoding of the receipt ended up being 238555 bytes, even though output in the journal is a single boolean, which is large. There seem to be more compact ways to represent the same, but unfortunately no documentation describing how to achieve it.

## User's Request
Add documentation on how to generate more compact/succinct proofs that could be uploaded to the blockchain and used in similar space-constrained environments.

**Comment by nazar-pc** [comment]
Looks like https://github.com/risc0/risc0/pull/1518 might actually address this

**Comment by pdg744** [comment]
The crate docs answer this question [here](https://docs.rs/risc0-zkvm/1.0.1/risc0_zkvm/trait.Prover.html#usage), and we have [another ticket](https://github.com/risc0/risc0/issues/1864) open to improve the dev docs coverage of this topic. 

Closing as I think #1864 is sufficient to track this.
