### ISSUE TITLE
Add docs about build process

### ISSUE THREAD

**Issue by Cardosaum** [risc0/risc0#1659]
## Overview

Currently we do not provide any explanation on how we perform our build process. Having a proper explanation on what happens when a user runs `cargo build` would be valuable both from an informational and practical perspective. 

By understanding the build process users have context on how host and guest code cooperate, where the `<guest>_ELF` and `<guest>_ID` constants come from and would save them time when trying to figure out how to get started with guest & host code development.

## Requirements

- [ ] Write a documentation page under "Writing your zkVM application" explaining the build process
- [ ] Explain how we use `build.rs` scripts to glue host and guest code together
- [ ] Explain how we embed `<guest>_ELF` and `<guest>_ID` constants as importable values in their host code
- [ ] Take inspiration on the ["putting it all together"](https://dev.risczero.com/api/next/zkvm/tutorials/io#putting-it-all-together) section of the I/O documentation, and write a section at the end of the build process doc showing how users can import elf and image id in practice ("This is how you can import ELF and image id, look at example X" kind of thing)

**Comment by pdg744** [comment]
transferring from dev rel board to platform board

**Comment by pdg744** [comment]
After checking in briefly with Austin about this, I'm inclined to close this as not planned. 
- Seems unclear whether users need/want this info
- Seems likely to be a high maintenance burden

If someone disagrees with that choice, feel free to re-open this or open a new ticket.
