### ISSUE TITLE
Support configurable MethodID code size limit

### ISSUE THREAD

**Issue by flaub** [risc0/risc0#166]
Currently, the `make-id` tool generates a table of hashes that have `kCodeDigestCount` entries. In #165, this count goes up by 4 which causes `make-id` to take 16x longer to run.

This feature would allow users to specify the maximum code size limit instead of always using `kCodeDigestCount`.

**Comment by flaub** [comment]
@jbruestle WDYT?

**Comment by jbruestle** [comment]
Seems like a good call.
