### ISSUE TITLE
[Feature] Support compression to CompactReceipt through the protobuf client/server API

### ISSUE THREAD

**Issue by nategraf** [risc0/risc0#1760]
## Feature

Support compression to `CompactReceipt` through the protobuf client/server API

## Motivation

Currently, compression to `CompactReceipt` is only possible when using `LocalProver` built using the `-F prove` flag.
As a result, users that install `r0vm` with `cargo-binstall` will not be able to produce compact (Groth16) receipts via the comperes method, even on x86 machines with Docker installed.

Note that users can still produce compact receipts by passing `receipt_kind = ReceiptKind::Compact` with their initial request to `prove`.

Related: https://github.com/risc0/risc0/issues/1749

**Comment by flaub** [comment]
@nategraf is this done with #1762?

**Comment by nategraf** [comment]
No. That doesn't have any methods to send a request to run the Groth16 step over protobuf.
