### ISSUE TITLE
Ceremony

### ISSUE THREAD

**Issue by UnicorNn1** [risc0/risc0#1778]
I made a report here before this and then I successfully switched the system by trying again, but I have another question, but I have another question, it shows 180 days for me, what is the reason for this? So there are more than 4 thousand pending members in front of me, is it normal that there is so much time? Is it normal for the system to work like this and how will we control it in the future and will it be enough until then?

**Comment by tzerrell** [comment]
We received much more interest in our ceremony than we anticipated. While we're delighted to see the enthusiasm, unfortunately it means that many people who wanted to contribute won't be able to participate (the ceremony ends in a few days). Unfortunately, this isn't really avoidable: our circuit is large, and so it takes a long time to download, compute, upload, and verify a contribution. Also, the work can't be done in parallel, and we can't require faster contributions as we are already pushing the limits of what sort of compute speed and (especially) internet connection speed we can expect from contributors -- a lot of people are timing out when they try to contribute.

The queue size and time are about what I would expect now that I know how many people want to contribute. We do not currently have plans for another ceremony, so we have not put much thought into what we would do differently in the future. If we do run another ceremony, we will definitely consider whether there are any optimizations we can make to get more contributions in, but there aren't any easy solutions here.
