### ISSUE TITLE
clarify usability of stark2snark on various architectures

### ISSUE THREAD

**Issue by pdg744** [risc0/risc0#1786]
In theory and according to our docs, one can use our tooling locally or remotely. 
But in practice, the stark2snark prover [only works on some hardware](https://github.com/risc0/risc0/issues/1749). 
This is a frequent point of confusion for users -- would be good to clarify the current status and recommended workflow(s) in the docs. 

- [x] add admonition to local proving page & proving options page 
- [x] add admonition to bonsai foundry template

**Comment by nuke-web3** [comment]
Related to #1749

**Comment by nuke-web3** [comment]
Idea: could we insert a compile time error to mention this issue until it's resolved for those using metal and other non-supported GPUs? Would help users a ton while this is not resolved

**Comment by sashaaldrick** [comment]
first PR opened and ready for review: #1952 @pdg744

**Comment by sashaaldrick** [comment]
#1952 merged

**Comment by sashaaldrick** [comment]
second PR opened for foundry template [#117](https://github.com/risc0/risc0-foundry-template/pull/117), waiting for review

**Comment by pdg744** [comment]
Thanks @sashaaldrick!
