### ISSUE TITLE
[Documentation] Have TSC confirmation doc link to audit details when ready

### ISSUE THREAD

**Issue by tzerrell** [risc0/risc0#1805]
## User's Objective

Users confirming the security of our trusted setup ceremony should be able to see relevant audit information.

## User's Obstacle

We are still working through getting our audits published, so users can't get to them yet. We therefore don't have links in the TSC docs because there's nothing to link to.

## User's Request

After the audits are published, link them in the TSC docs.

**Comment by pdg744** [comment]
Is [this](https://github.com/risc0/security/blob/main/auditing/mainnet_verifier/hexens_verifiercontract_20240605.pdf) the appropriate asset to link to?

**Comment by tzerrell** [comment]
Addressed by https://github.com/risc0/risc0/pull/1981
