### ISSUE TITLE
Automatic Retry for Trusted Setup Ceremony Command

### ISSUE THREAD

**Issue by duongnq2798** [risc0/risc0#1822]
# Automatic Retry for Trusted Setup Ceremony Command

## Feature
Implement an automatic retry mechanism for the Trusted Setup Ceremony command in cases where no contribution is available at the time of the request.

## Motivation
Currently, when users attempt to contribute to the Trusted Setup Ceremony, they often encounter a warning message stating: "Unfortunately, there is no ceremony for which you can make a contribution at this time. Please try again later." This message leads to the command line window automatically closing, which is not user-friendly. By introducing an automatic retry option, users will have a smoother experience, reducing frustration and encouraging participation in the ceremony.

## Implementation
1. **Automatic Exit Option:** Provide users with the choice to automatically exit the command line if no contribution is available.
2. **Automatic Restart Option:** Offer users the option to automatically restart the command in case of no available contributions. This feature ensures that users do not have to manually initiate the command again, improving convenience and efficiency.

### Code Block
```bash
#!/bin/bash

while true; do
    # Run the command
    npx phase2cli contribute

    # Check the exit status of the command
    if [ $? -eq 0 ]; then
        echo "Command executed successfully."
        break  # Exit the loop if the command succeeds
    else
        echo "Command failed. Retrying in 30 seconds..."
        sleep 30  # Wait for 30 seconds before retrying
    fi
done
```
![image](https://github.com/risc0/risc0/assets/59973311/af26bcd0-53d9-494f-b801-964c1e6b1a39)

**Comment by tzerrell** [comment]
Our trusted setup ceremony was run using p0tion (https://github.com/privacy-scaling-explorations/p0tion); the phase2cli code is not part of this repository.
