### ISSUE TITLE
[Devex] Issue templates to direct to support, FAQ, and other resources

### ISSUE THREAD

**Issue by nuke-web3** [risc0/risc0#1835]
https://github.com/risc0/risc0/tree/main/.github/ISSUE_TEMPLATE has pathways to file a bug or a feature request. I would like to add a link to external resources there as well to encourage search for solutions and/or request support in a way that is possible to do some minimal analytics on. 

For example https://github.com/paritytech/polkadot-sdk/issues/new/choose has a link to their stack exchange to search for solutions, and if nothing relevant, ask a new question. I think we could do the same here linking to discord as the support location via a link that we can monitor for hits and also I think use to assign a role that automatically gets them write access to otherwise read-only channels for R0 devs to chat & ask questions.

Happy to make a PR, but wanted to get feedback on what else might be linked to if anything (maybe our docs?) and consider what, if anything, should be modified in our templates to compliment that change.

**Comment by SchmErik** [comment]
@nuke-web3 we merged #2016 does that mean we can close this issue? if so, feel free to close this issue
