### ISSUE TITLE
add software security practices to security model doc

### ISSUE THREAD

**Issue by pdg744** [risc0/risc0#1859]
We should add mentions of our software security practices (including audits) to the [security model page in our dev docs](https://github.com/risc0/risc0/blob/main/website/api/security-model.md).
Kevin is working on this.

**Comment by nuke-web3** [comment]
related to https://www.risczero.com/blog/risc-zero-take-the-rekt-test

**Comment by pdg744** [comment]
Ya, related to that blogpost. 

To add a bit more context, the aim is to create a unified place users can go to get a complete description of the security of our products. The `security-model.md` page currently does that pretty well with the cryptographic security model. The vision is to re-name that doc to `cryptographic-security.md`, and to add a `software-security.md` doc alongside it (in the `reference` section of the sidebar.

**Comment by pdg744** [comment]
@kevinnassery any updates on this? 

Would be really nice to fix the fact that neither the `risc0/security` repo nor the `rekt test` blogpost are findable from dev docs. 

tagging @morgangibbs87 also for visibility, given his new role

**Comment by pdg744** [comment]
We landed a "secure software development lifecycle" doc adjacent to the cryptographic security model doc. 
https://dev.risczero.com/api/secure-sdlc
