### ISSUE TITLE
Fix dead link

### ISSUE THREAD

**Issue by ucskyship** [risc0/risc0#1958]
![image](https://github.com/risc0/risc0/assets/103766355/6659c252-6c6d-4a40-8ba2-7fed4cf25f8f)
![Screenshot 2024-06-11 204727](https://github.com/risc0/risc0/assets/103766355/b922020f-3a8d-4815-bdd3-eb7c2f07e4fd)

**Comment by pdg744** [comment]
Seems like this is referencing the link in [this section](https://github.com/risc0/risc0/tree/main/risc0/cargo-risczero#new) which seems to be working now.
