### ISSUE TITLE
Revise blockchain docs & coprocessor blog to reflect deprecation of relay

### ISSUE THREAD

**Issue by pdg744** [risc0/risc0#1978]
- [x] Remove stale architecture references from coprocessor blog post 
- [x] Remove dev docs links that point to twitter coprocessor post #1992 

Here's the Slack message from Victor that prompted this issue: 
<img width="490" alt="image" src="https://github.com/risc0/risc0/assets/15272444/c1002657-3b13-4605-a257-e87881aeeec3">

**Comment by nuke-web3** [comment]
I want to make a workshop for ETHCC that highlights composition - any chance this can get some priority? 💟

**Comment by pdg744** [comment]
I've asked Santiago to remove those sections, so we can go ahead and continue pointing to the blog post. 
And we can stop pointing to the twitter page, in favor of the blogpost. 

With that done, I think we're in a position of "no obvious fires" with respect to our docs on this topic -- I don't think users will find any lingering mentions of the relay. 

Before we close this, let's make some improvement to the description of Step 3 [here](https://dev.risczero.com/api/blockchain-integration/bonsai-on-eth#overview), in order to help users find their way to the [associated section of the foundry template](https://github.com/risc0/risc0-foundry-template/tree/main/apps)

**Comment by pdg744** [comment]
> you mentioned that perhaps all that is needed is removing a few sections. Happy to help if I can be show the way baby yoda emoji

This is a question for Santiago -- I am happily ignorant of the process of posting or editing blog posts.
