### ISSUE TITLE
Can I using this crate with web framework like `actix-web`

### ISSUE THREAD

**Issue by sweatpotato13** [risc0/risc0#2011]
I would like to use this crate to verify the operation of a REST API server implemented based on Rust, and I am wondering if it is possible.

So I would like to ask if it is possible to use this with crates like Actix-web.

**Comment by nuke-web3** [comment]
You can see what of the top 1000 crates work out of the box on https://reports.risczero.com/crates-validation:

![image](https://github.com/risc0/risc0/assets/35669742/23c4cf6f-4825-46fb-82ee-784eafd3414c)

> `compile_error!("Socket2 doesn't support the compile target");`

At this time it seems like there may be some issues using that crate _in the guest_ - most likely there would be a way to work around this. 

This kind of question is much better for our discord that has a dedicated dev-questions/support-forum channel : https://discord.com/invite/risczero 

See you in there @sweatpotato13 :grinning:
