### ISSUE TITLE
rust-std: Add support for `thread_local_key`

### ISSUE THREAD

**Issue by flaub** [risc0/risc0#207]
From discord:

Currently, any crate which depends on `once_cell` (including `std::collections::HashMap`) will compile but experience a runtime panic because the method thread_local_key is unimplemented.

```
Exception { what: "panicked at 'should not be used on this target', /risc0-rust-starter/target/debug/build/methods-e1d0c7ab6d906214/out/rust-std_5394976e3be5c2fbe950f41f75eb392cd888657933629544e0a55a75bb0e59d9/library/std/src/sys/unsupported/thread_local_key.rs:25:5" }'
```

Since the zkvm is single-threaded, it seems like this should be relatively straightforward.

**Comment by shkoo** [comment]
Should be fixed by #216
