### ISSUE TITLE
Revm 11.0.0 doesn't work with rustc v1.78, updating toolchain to v1.79 resolves the issue

### ISSUE THREAD

**Issue by Pasifaee** [risc0/risc0#2088]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Discord first?

- [X] This is not a support question.

### Motivation

I want to update revm to version 11.0.0 but that causes `error: inline-const is experimental`. This error is resolved with rustc 1.79, but the latest version of risc0 toolchain is 1.78.

### Request

It'd be great if rustc gets updated to 1.79 in the toolchain.

### Are you willing to help with this request?

No.

**Comment by SchmErik** [comment]
@Pasifaee I've created a pre-release of the 1.79 toolchain. You can download by running `cargo risczero install --version r0.1.79.0` this toolchain breaks the `env::send_recv(...)` functionality but if your project doesn't use it, it should be fine to use. Let me know if you have any issues with it. We're still trying to work out this issue that we're seeing before we mark it as latest release.

**Comment by SchmErik** [comment]
update - there's a small issue that I'll fix tomorrow and the above install command should work. I'll chime in when I fix it

**Comment by SchmErik** [comment]
Update: @Pasifaee this has been fixed and the toolchain is ready as a pre-release the install command i mentioned before should work

**Comment by Pasifaee** [comment]
Thank you!!
