### ISSUE TITLE
Non-succinct recursion support

### ISSUE THREAD

**Issue by rezahsnz** [risc0/risc0#2124]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Discord first?

- [X] This is not a support question.

### Motivation

The current recursive proving stack [lift->join->identity_p254->compress](https://github.com/risc0/risc0/blob/90a0b816d2ecdb1f643b639b1c1e352e824749eb/website/api/recursion.md) favours STARK-to-SNARK settings where proofs are destined to be **verified on-chain**. There may however exist other areas that this is not the case. `General verifiable computing` is one such example where people may be interested to dispatch proving tasks and combine them into a final STARK proof. Right now, to do proof aggregation, we have no way but  to use SNARKs for this.

### Request

I request that you add a STARK-only recursion regime for off-chain and other potential application areas as well. 

### Solution

Feels like a single call to [verifiy_integrity_with_context](https://docs.rs/risc0-zkvm/latest/risc0_zkvm/struct.SegmentReceipt.html#method.verify_integrity_with_context) in the [CompositeReceipt](https://docs.rs/risc0-zkvm/latest/risc0_zkvm/struct.CompositeReceipt.html) struct is the way to go. But since it is marked as `#[non_exhaustive]`, outsiders cannot instantiate the struct and thus STARK-only proof aggregation is not possible for the time being.

### Are you willing to help with this request?

Maybe... (I have elaborated on how above)

**Comment by pdg744** [comment]
You can opt for a STARK-only recursion by setting the `ReceiptKind` to `SuccinctReceipt`. 

See: https://docs.rs/risc0-zkvm/latest/risc0_zkvm/enum.ReceiptKind.html

**Comment by pdg744** [comment]
Ahh sorry I should have linked here: https://docs.rs/risc0-zkvm/1.0/risc0_zkvm/struct.ProverOpts.html
