### ISSUE TITLE
Compile failed for Hello_World

### ISSUE THREAD

**Issue by ludete** [risc0/risc0#2183]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Discord first?

- [X] This is not a support question.

### Description of bug

.cargo/registry/src/github.com-1ecc6299db9ec823/ahash-0.8.11/src/random_state.rs:463:5
multiply:     |
multiply: 463 | /     fn hash_one<T: Hash>(&self, x: T) -> u64 {
multiply: 464 | |         RandomState::hash_one(self, x)
multiply: 465 | |     }
multiply:     | |_____^
multiply:     |
multiply:     = note: see issue #86161 <https://github.com/rust-lang/rust/issues/86161> for more information
multiply:     = help: add `#![feature(build_hasher_simple_hash_one)]` to the crate attributes to enable
multiply:
multiply: For more information about this error, try `rustc --explain E0658`.
multiply: error: could not compile `ahash` (lib) due to 1 previous error
multiply: warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `hello-world-methods v0.1.0 (/Users/yongxin.yao/bitlayer/risc0/examples/hello-world/methods)`

### Steps to reproduce

reproduce step by step

1. cd risc0/examples/hello-world
2. cargo build

------------------

Build ENV

1. rustc --version
rustc 1.77.2 (25ef9e3d8 2024-04-09)

2. cargo --version
cargo 1.77.2 (e52e36006 2024-03-26)

3. cargo risczero --version
cargo-risczero 1.0.5

**Comment by nahoc** [comment]
@ludete have you tried running `cargo run --release`?

**Comment by SchmErik** [comment]
> ### Is there an existing issue?
> 
>     * [x]  I have searched the existing issues
> 
> 
> ### Experiencing problems? Have you tried our Discord first?
> 
>     * [x]  This is not a support question.
> 
> 
> ### Description of bug
> 
> .cargo/registry/src/github.com-1ecc6299db9ec823/ahash-0.8.11/src/random_state.rs:463:5 multiply: | multiply: 463 | / fn hash_one<T: Hash>(&self, x: T) -> u64 { multiply: 464 | | RandomState::hash_one(self, x) multiply: 465 | | } multiply: | |_____^ multiply: | multiply: = note: see issue #86161 [rust-lang/rust#86161](https://github.com/rust-lang/rust/issues/86161) for more information multiply: = help: add `#![feature(build_hasher_simple_hash_one)]` to the crate attributes to enable multiply: multiply: For more information about this error, try `rustc --explain E0658`. multiply: error: could not compile `ahash` (lib) due to 1 previous error multiply: warning: build failed, waiting for other jobs to finish... error: failed to run custom build command for `hello-world-methods v0.1.0 (/Users/yongxin.yao/bitlayer/risc0/examples/hello-world/methods)`
> ### Steps to reproduce
> 
> reproduce step by step
> 
>     1. cd risc0/examples/hello-world
> 
>     2. cargo build
> 
> 
> Build ENV
> 
>     1. rustc --version
>        rustc 1.77.2 (25ef9e3d8 2024-04-09)
> 
>     2. cargo --version
>        cargo 1.77.2 (e52e36006 2024-03-26)
> 
>     3. cargo risczero --version
>        cargo-risczero 1.0.5

hey, sorry about the late response - it looks like you're trying to use an older guest compiler. Could you run `cargo risczero install --version r0.1.78.0` and build the program again to see if this fixes the issue?

**Comment by ludete** [comment]
> @ludete have you tried running `cargo run --release`?

This error occurs after the command is run.

**Comment by ludete** [comment]
> hey, sorry about the late response - it looks like you're trying to use an older guest compiler. Could you run `cargo risczero install --version r0.1.78.0` and build the program again to see if this fixes the issue?

have fixed by the below command:

`cargo risczero build-toolchain --version v2024-04-22.0.`

**Comment by ludete** [comment]
Oh, a notice that the `link with discord` has been invalid in the official website.
