### ISSUE TITLE
`SessionInfo` should include a method to construct the associated `ReceiptClaim`

### ISSUE THREAD

**Issue by nategraf** [risc0/risc0#2267]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Discord first?

- [X] This is not a support question.

### Request

Implement a `claim` method or field on `SessionInfo` to get the full `ReceiptClaim`.

### Are you willing to help with this request?

Yes!

**Comment by flaub** [comment]
Why would this go on a `SessionInfo`?

**Comment by nategraf** [comment]
`ReceiptClaim` is generally the canonical structure we use to encode the results of a guest execution. If it's assumed that execution was successful, complete, and unconditional, then the image ID and journal is sufficient. The claim encodes a much wider range of outcomes though.

I'm currently using the executor in testing. I could also use the prover, but then I need to set the `RISC0_DEV_MODE` to have tests work as expected (and either fail because I'm not on x86 or take a very long time), and globally disables real proving.

Here is the pattern I'm currently using in tests to produce a fake receipt
```rust
    /// Produce a fake receipt for the guest execution.
    fn mock_prove(env: ExecutorEnv, elf: &[u8], id: impl Into<Digest>) -> anyhow::Result<Receipt> {
        // TODO: Change this to use SessionInfo::claim or another method.
        // See https://github.com/risc0/risc0/issues/2267.
        let session = ExecutorImpl::from_elf(env, elf)?.run()?;
        Ok(Receipt::new(
            InnerReceipt::Fake(FakeReceipt::new(session.claim()?)),
            session.journal.bytes,
        ))
    }
```
