### ISSUE TITLE
rzup msrv issue

### ISSUE THREAD

**Issue by austinabell** [risc0/risc0#2326]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Discord first?

- [X] This is not a support question.

### Description of bug

Noted that this error was hit:
```
   Compiling gix-submodule v0.14.0
error[E0658]: use of unstable library feature 'io_error_downcast'
  --> /home/yue/.cargo/registry/src/index.crates.io-6f17d22bba15001f/binstalk-downloader-0.13.1/src/download.rs:47:13
   |
47 |         err.downcast::<DownloadError>()
   |             ^^^^^^^^
   |
   = note: see issue #99262 <https://github.com/rust-lang/rust/issues/99262> for more information
   = help: add #![feature(io_error_downcast)] to the crate attributes to enable
   = note: this compiler was built on 2024-04-17; consider upgrading it if it is out of date
```

To avoid these 

### Steps to reproduce

```
rzup
```
with `<1.79` rust version seems like it would be the issue. Perhaps worth pinning `cargo-binstall` to a version with a stable msrv? Seems like `1.6.9` is the recommended one, with a `1.70` msrv. Unclear how tedious this would be to maintain if those versions outdated though.

**Comment by nuke-web3** [comment]
IIUC we do not use `cargo-binstall` any more, so this should not be an issue. Please reopen if it's still relevant :pray:
