### ISSUE TITLE
"rzup install" needlessly consumes memory

### ISSUE THREAD

**Issue by conduition** [risc0/risc0#2446]
I encountered this problem when trying to install Risc0 on a VPS with only a few GB of memory. `rzup install` quickly consumes the machine's entire available memory.

![rzuip](https://github.com/user-attachments/assets/356d9dd8-4431-44a9-834e-4a374129fcf9)

This code is the culprit:

```rust
        let mut file = fs::File::create(&temp_file_path)?;
        let content = response.bytes().await?;

        verbose_msg!(format!(
            "Writing contents to file {}",
            temp_file_path.display()
        ));

        file.write_all(&content)?;
```

https://github.com/risc0/risc0/blob/2ba504fddd84376235d335ec4db6b2353d967fc9/rzup/src/toolchain.rs#L191

When downloading large tarballs, the download should be streamed to a file on disk, not buffered into memory. 

If you wanted to be even more efficient, you could stream the download through a tarball decompression stream handler. But i think the bare minimum is at least buffering to disk instead of memory.

**Comment by flaub** [comment]
@hmrtn @SchmErik I think if we moved to using the `downloader` crate instead of using `reqwest` directly, this would avoid downloading into memory before writing to disk and instead write chunks incrementally.
