### ISSUE TITLE
Executor Statistics environment flag is invalid

### ISSUE THREAD

**Issue by SkymanOne** [risc0/risc0#2457]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Discord first?

- [X] This is not a support question.

### Description of bug

According to https://dev.risczero.com/api/zkvm/quickstart to enable executor statistics, one should set `RUST_LOG="[executor]=info"`. However, this does not seem to work on my machine `Macbook Pro M1`. Instead, `RUST_LOG=info` seems to do the job.

Crate version: `1.1.2`

### Steps to reproduce

1. Create a new project with `cargo risczero new ...`
2. Run `RISC0_DEV_MODE=1 RUST_LOG="[executor]=info" cargo run --release`
3. Run RISC0_DEV_MODE=1 RUST_LOG=info cargo run --release

**Comment by austinabell** [comment]
These docs seem up to date, but I do notice that an old version of the docs has this recommendation (`RUST_LOG=[executor]=info`).

These logs follow standard RUST_LOG semantics, so feel free to filter the logs you see using that!

**Comment by SkymanOne** [comment]
Thanks, that explains it. I left the issue open to close it with PR, which updates the docs in other places.
