### ISSUE TITLE
"Guest panicked: sys_getenv is disabled" for anyhow error used guest code

### ISSUE THREAD

**Issue by spartucus** [risc0/risc0#2627]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Discord first?

- [X] This is not a support question.

### Description of bug

When I use anyhow error in the guest code, the prove will report an error:
```shell
called `Result::unwrap()` on an `Err` value: Guest panicked: sys_getenv is disabled; can be enabled with the sys-getenv feature flag on risc0-zkvm-platform
```
 If I don't use `anyhow::anyhow!`, it succeed to run the prover. 
 
 Env: 
 * risc0 1.2.0
 * risc0-zkvm: 1.2.0.
 * Mac M4
 * MacOS: 15.1.1 

### Steps to reproduce

Install the risc0 1.2.0, and clone the repo, https://github.com/spartucus/risc0-anyhow-error/blob/main/methods/guest/src/main.rs#L10, just run `cargo run`.

**Comment by flaub** [comment]
I'm guessing it's related to this: https://github.com/dtolnay/anyhow/blob/master/src/backtrace.rs#L200

**Comment by spartucus** [comment]
Somehow, this repo can run in risc0 v1.1.2

**Comment by nategraf** [comment]
So, there is an allowlist of environment variables that can be passed to the guest, starting in 1.2.0. This is to make it less likely that a program will exhibit unintended behavior that might compromise its soundness. `RUST_BACKTRACE` is on the allowlist, but I neglected to add `RUST_LIB_BACKTRACE`. I've opened https://github.com/risc0/risc0/pull/2636 and will check to see that this resolves the issue.

**Comment by nategraf** [comment]
Ok, I confirmed the original issue and applied the following patch to use #2636 
```diff
index 20b716c..7b55f0e 100644
--- a/host/Cargo.toml
+++ b/host/Cargo.toml
@@ -5,6 +5,6 @@ edition = "2021"

 [dependencies]
 methods = { path = "../methods" }
-risc0-zkvm = { version = "1.2.0" }
-tracing-subscriber = { version = "0.3", features = ["env-filter"] }
+risc0-zkvm = { git = "https://github.com/risc0/risc0", branch = "victor/fix-2627" }
 serde = "1.0"
+tracing-subscriber = { version = "0.3", features = ["env-filter"] }
diff --git a/methods/Cargo.toml b/methods/Cargo.toml
index aa1546b..9ee6ade 100644
--- a/methods/Cargo.toml
+++ b/methods/Cargo.toml
@@ -4,7 +4,7 @@ version = "0.1.0"
 edition = "2021"

 [build-dependencies]
-risc0-build = { version = "1.2.0" }
+risc0-build = { git = "https://github.com/risc0/risc0", branch = "victor/fix-2627" }

 [package.metadata.risc0]
 methods = ["guest"]
diff --git a/methods/guest/Cargo.toml b/methods/guest/Cargo.toml
index 6324bbe..d1aef6c 100644
--- a/methods/guest/Cargo.toml
+++ b/methods/guest/Cargo.toml
@@ -6,5 +6,5 @@ edition = "2021"
 [workspace]

 [dependencies]
-risc0-zkvm = { version= "1.2.0", default-features = false, features = ['std'] }
-anyhow = "1.0"
\ No newline at end of file
+anyhow = "1.0"
+risc0-zkvm = { git = "https://github.com/risc0/risc0", branch = "victor/fix-2627", default-features = false, features = ['std'] }
```
I confirmed that this fixes the issue
