### ISSUE TITLE
Circuit file names and line numbers leak into verifier release builds and takes up a lot of rodata space

### ISSUE THREAD

**Issue by stskeeps** [risc0/risc0#307]
Example from a WASM release build:

`cirgen/circuit/rv32im/top.cpp:18cirgen/components/bytes.cpp:21cirgen/components/bytes.cpp:34cirgen/components/bytes.cpp:37cirgen/components/bytes.cpp:82cirgen/components/bytes.cpp:83cirgen/circuit/rv32im/body.cpp:14cirgen/circuit/rv32im/body.cpp:17cirgen/circuit/rv32im/body.cpp:18cirgen/circuit/rv32im/body.cpp:43cirgen/circuit/rv32im/body.cpp:29cirgen/circuit/rv32im/body.cpp:30cirgen/circuit/rv32im/body.cpp:31./cirgen/components/onehot.h:35cirgen/circuit/rv32im/decode.cpp:11cirgen/circuit/rv32im/decode.cpp:12cirgen/circuit/rv32im/decode.cpp:13cirgen/circuit/rv32im/decode.cpp:15cirgen/circuit/rv32im/decode.cpp:23cirgen/circuit/rv32im/compute.cpp:17cirgen/circuit/rv32im/compute.cpp:45cirgen/circuit/rv32im/decode.cpp:71cirgen/circuit/rv32im/compute.cpp:134cirgen/components/u32.cpp:59./cirgen/circuit/rv32im/rv32im.inl:37./cirgen/circuit/rv32im/rv32im.inl:44cirgen/circuit/rv32im/decode.cpp:89./cirgen/circuit/rv32im/rv32im.inl:50./cirgen/circuit/rv32im/rv32im.inl:56./cirgen/circuit/rv32im/rv32im.inl:57./cirgen/circuit/rv32im/rv32im.inl:58./cirgen/circuit/rv32im/rv32im.inl:59cirgen/circuit/rv32im/memio.cpp:80./cirgen/circuit/rv32im/rv32im.inl:82cirgen/components/u32.cpp:183cirgen/components/u32.cpp:228cirgen/components/u32.cpp:232cirgen/circuit/rv32im/ecall.cpp:128cirgen/circuit/rv32im/ecall.cpp:133cirgen/circuit/rv32im/ecall.cpp:40cirgen/circuit/rv32im/ecall.cpp:42cirgen/circuit/rv32im/ecall.cpp:94cirgen/circuit/rv32im/sha.cpp:195cirgen/circuit/rv32im/sha.cpp:196cirgen/circuit/rv32im/sha.cpp:104cirgen/circuit/rv32im/sha.cpp:111cirgen/circuit/rv32im/sha.cpp:286cirgen/circuit/rv32im/sha.cpp:290cirgen/circuit/rv32im/sha.cpp:319cirgen/circuit/rv32im/sha.cpp:364cirgen/circuit/rv32im/ffpu.cpp:37cirgen/circuit/rv32im/ffpu.cpp:70cirgen/components/ram.cpp:21cirgen/c
omponents/ram.cpp:22cirgen/circuit/rv32im/ffpu.cpp:41cirgen/circuit/rv32im/ffpu.cpp:45cirgen/circuit/rv32im/rv32im.cpp:18Top/Code/OneHot/Reg1(./cirgen/components/mux.h:37)Top/Code/OneHot/Reg1(cirgen/circuit/rv32im/top.cpp:18)Top/Code/Mux/1/Reg(./cirgen/compiler/edsl/com
ponent.h:85)cirgen/components/bytes.cpp:22cirgen/components/bytes.cpp:102cirgen/components/bytes.cpp:103Top/Mux/1/BytesSetup/PlonkBody/BytesPlonkElement20/Reg(./cirgen/compiler/edsl/component.h:85)Top/Mux/1/BytesSetup/PlonkBody/BytesPlonkElement20/Reg1(./cirgen/compiler
/edsl/component.h:85)cirgen/components/bytes.cpp:44cirgen/components/bytes.cpp:45cirgen/components/bytes.cpp:46cirgen/components/bytes.cpp:47cirgen/components/bytes.cpp:48Top/Mux/1/BytesSetup/PlonkBody/BytesPlonkElement1/Reg(./cirgen/compiler/edsl/edsl.h:110)Top/Mux/1/B
ytesSetup/PlonkBody/BytesPlonkElement1/Reg1(./cirgen/compiler/edsl/edsl.h:110)Top/Mux/1/BytesSetup/PlonkBody/BytesPlonkElement2/Reg(./cirgen/compiler/edsl/edsl.h:110)Top/Mux/1/BytesSetup/PlonkBody/BytesPlonkElement2/Reg1(./cirgen/compiler/edsl/edsl.h:110)Top/Mux/1/Bytes
Setup/PlonkBody/BytesPlonkElement3/Reg(./cirgen/compiler/edsl/edsl.h:110)Top/Mux/1/BytesSetup/PlonkBody/BytesPlonkElement3/Reg1(./cirgen/compiler/edsl/edsl.h:110)Top/Mux/1/BytesSetup/PlonkBody/BytesPlonkElement4/Reg(./cirgen/compiler/edsl/edsl.h:110)Top/Mux/1/BytesSetup
/PlonkBody/BytesPlonkElement4/Reg1(./cirgen/compiler/edsl/edsl.h:110)Top/Mux/1/BytesSetup/PlonkBody/BytesPlonkElement5/Reg(./cirgen/compiler/edsl/edsl.h:110)Top/Mux/1/BytesSetup/PlonkBody/BytesPlonkElement5/Reg1(./cirgen/compiler/edsl/edsl.h:110)Top/Mux/1/BytesSetup/Plo
nkBody/BytesPlonkElement6/Reg(./cirgen/compiler/edsl/edsl.h:110)Top/Mux/1/BytesSetup/PlonkBody/BytesPlonkElement6/Reg1(./cirgen/compiler/edsl/edsl.h:110)Top/Mux/1/BytesSetup/PlonkBody/BytesPlonkElement7/Reg(./cirgen/compiler/edsl/edsl.h:110)Top/Mux/1/BytesSetup/PlonkBod
y/BytesPlonkElement7/Reg1(./cirgen/compiler/edsl/edsl.h:110)cirgen/components/bytes.cpp:112cirgen/components/bytes.cpp:113cirgen/components/bytes.cpp:110cirgen/components/bytes.cpp:116./cirgen/components/mux.h:37Top/Code/OneHot/Reg2(./cirgen/components/mux.h:37)Top/Code
/Mux/2/Reg1(./cirgen/compiler/edsl/component.h:85)cirgen/components/bytes.cpp:87Top/Code/Mux/2/Reg2(./cirgen/compiler/edsl/component.h:85)Top/Code/Reg(./cirgen/compiler/edsl/component.h:85)cirgen/components/u32.cpp:28cirgen/components/ram.cpp:104cirgen/components/ram.cp
p:105cirgen/components/ram.cpp:106Top/Code/Mux/2/Reg3(./cirgen/compiler/edsl/component.h:85)Top/Code/Mux/2/Reg4(./cirgen/compiler/edsl/component.h:85)cirgen/circuit/rv32im/top.cpp:35Top/Code/Mux/2/Reg5(./cirgen/compiler/edsl/component.h:85)Top/Code/Mux/2/Reg6(./cirgen/c
ompiler/edsl/component.h:85)Top/Code/OneHot/Reg3(./cirgen/components/mux.h:37)./cirgen/components/bits.h:57cirgen/circuit/rv32im/body.cpp:22cirgen/circuit/rv32im/body.cpp:23Top/Code/OneHot/Reg4(./cirgen/components/mux.h:37)Top/Mux/4/BytesBody/PlonkBody/BytesPlonkElement
/Reg(cirgen/components/bytes.cpp:78)Top/Mux/4/BytesBody/PlonkBody/BytesPlonkElement/Reg1(cirgen/components/bytes.cpp:78)cirgen/circuit/rv32im/body.cpp:28cirgen/circuit/rv32im/body.cpp:27Top/Mux/4/BytesBody/PlonkBody/BytesPlonkElement1/Reg(cirgen/components/bytes.cpp:78)
Top/Mux/4/PCReg/Twit/Reg(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/PCReg/Twit1/Reg(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/OneHot/Reg(./cirgen/components/mux.h:37)cirgen/circuit/rv32im/compute.cpp:112Top/Mux/4/Mux/0/ComputeCycle/RamBody/PlonkBody/RamPlonkE
lement/U32Reg/Reg(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/RamBody/PlonkBody/RamPlonkElement/U32Reg/Reg1(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/RamBody/PlonkBody/RamPlonkElement/U32Reg/Reg2(./cirgen/compiler/edsl/com
ponent.h:85)Top/Mux/4/Mux/0/ComputeCycle/RamBody/PlonkBody/RamPlonkElement/U32Reg/Reg3(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/Decoder/Bit2/Reg(./cirgen/compiler/edsl/component.h:85)cirgen/circuit/rv32im/decode.cpp:53Top/Mux/4/Mux/0/ComputeCyc
le/Decoder/Twit1/Reg(./cirgen/compiler/edsl/component.h:85)cirgen/circuit/rv32im/decode.cpp:57Top/Mux/4/Mux/0/ComputeCycle/Decoder/Bit1/Reg(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/Decoder/Bit/Reg(./cirgen/compiler/edsl/component.h:85)Top/Mux/4
/Mux/0/ComputeCycle/Decoder/Twit/Reg(./cirgen/compiler/edsl/component.h:85)cirgen/circuit/rv32im/decode.cpp:30Top/Mux/4/Mux/0/ComputeCycle/Decoder/Bit5/Reg(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/Decoder/Bit4/Reg(./cirgen/compiler/edsl/compone
nt.h:85)cirgen/circuit/rv32im/decode.cpp:31Top/Mux/4/Mux/0/ComputeCycle/Decoder/Twit2/Reg(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/Decoder/Bit3/Reg(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/Decoder/Twit4/Reg(./cirgen/co
mpiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/Decoder/Twit3/Reg(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/Decoder/Bit6/Reg(./cirgen/compiler/edsl/component.h:85)cirgen/circuit/rv32im/decode.cpp:32Top/Mux/4/Mux/0/ComputeCycle/Decoder/Bi
t7/Reg(./cirgen/compiler/edsl/component.h:85)cirgen/circuit/rv32im/decode.cpp:49Top/Mux/4/Mux/0/ComputeCycle/Decoder/Twit5/Reg(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/Decoder/Twit7/Reg(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/Comp
uteCycle/Decoder/Twit6/Reg(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/Decoder/Bit8/Reg(./cirgen/compiler/edsl/component.h:85)cirgen/circuit/rv32im/decode.cpp:33Top/Mux/4/Mux/0/ComputeCycle/Decoder/Reg(./cirgen/compiler/edsl/edsl.h:110)cirgen/circ
uit/rv32im/decode.cpp:37Top/Mux/4/Mux/0/ComputeCycle/RamBody/PlonkBody/RamPlonkElement1/U32Reg/Reg(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/RamBody/PlonkBody/RamPlonkElement1/U32Reg/Reg1(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/Com
puteCycle/RamBody/PlonkBody/RamPlonkElement1/U32Reg/Reg2(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/RamBody/PlonkBody/RamPlonkElement1/U32Reg/Reg3(./cirgen/compiler/edsl/component.h:85)cirgen/circuit/rv32im/decode.cpp:41cirgen/circuit/rv32im/comp
ute.cpp:135Top/Mux/4/Mux/0/ComputeCycle/RamBody/PlonkBody/RamPlonkElement2/U32Reg/Reg(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/RamBody/PlonkBody/RamPlonkElement2/U32Reg/Reg1(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/Ram
Body/PlonkBody/RamPlonkElement2/U32Reg/Reg2(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/RamBody/PlonkBody/RamPlonkElement2/U32Reg/Reg3(./cirgen/compiler/edsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/ComputeControl/U32Reg/Reg(./cirgen/compiler/e
dsl/component.h:85)Top/Mux/4/Mux/0/ComputeCycle/ComputeControl/U32Reg/Reg1(./cirgen/compiler/edsl/component.h:85)`

**Comment by intoverflow** [comment]
Ironically, the [constant that contains all of these strings](https://github.com/risc0/risc0/blob/main/risc0/circuit/rv32im/src/poly_ext.rs) isn't `pub`, and [the only code I can find](https://github.com/risc0/risc0/blob/b94ff0e6ca26585db3df4baccd3559c6fc2cc5d6/risc0/zkp/src/adapter.rs#L143) that has access to these values ignores them (!)

Seems like something that could be safely removed ...
