### ISSUE TITLE
Where is code of rule checks to validate RISC computation?

### ISSUE THREAD

**Issue by wangtsiao** [risc0/risc0#322]
Hi, I am reading the documentation of [RISC Zero](https://www.risczero.com/docs/explainers/proof-system/constructing-a-seal#lesson-2-rule-checks-to-validate-a-computation) where said the below description.
> In the full RISC-V implementation, the rules make up what it means to execute RISC-V instructions properly (i.e. checking that the program counter increments after every instruction). We check thousands of rules in order to validate the execution trace.

I want to know what those rules are, and I tried to find them in implementation but did not find them. Does anyone know where is the implementation of those rules?

**Comment by SchmErik** [comment]
Hi @wangtsiao the code is located in https://github.com/risc0/risc0/tree/main/risc0/circuit/rv32im/cxx in files such as step_verify_mem.cpp. The file that contains the rule checks is generated from an eDSL so it might be difficult to understand

**Comment by wangtsiao** [comment]
Hi @SchmErik thanks, what is the eDSL please, and does the original eDSL code open source?

**Comment by SchmErik** [comment]
The eDSL is called Zirgen and is used to program our riscv circuit. Unfortunately this is currently closed source. I'm not sure if we will release it because we are also working on overhauling this language. Eventually, the goal is to make the circuit language open source but we are not there yet

**Comment by pdg744** [comment]
You may also want to check out Frank's talk @ ZK Proof: https://www.youtube.com/watch?v=TsP14-hI_W0
