### ISSUE TITLE
Proof verification in guest?

### ISSUE THREAD

**Issue by matthiasgoergens** [risc0/risc0#338]
What's the status of running the proof verifier as part of a guest?  If it's supported, do you have an example showing how it's done?

https://github.com/risc0/risc0/pull/259 added a tests for that, but it looks like c856a6890a1a84502274ba86586ab3a584327494 undid that?  https://github.com/risc0/risc0/pull/337/files seems to show some very recent work again in that direction.

Thanks for your help!

@flaub

**Comment by ferjcast** [comment]
Hi. Could you solve it in the end? I'm interested in that as well. Thanks

**Comment by matthiasgoergens** [comment]
I haven't solved it.

**Comment by flaub** [comment]
This should be possible as of https://github.com/risc0/risc0/pull/1776, and will part of the upcoming 1.0 release.
