### ISSUE TITLE
Broken method risc0_zkvm::guest::sha::digest

### ISSUE THREAD

**Issue by nategraf** [risc0/risc0#356]
Based on the test results from this PR https://github.com/risc0/risc0-rust-examples/pull/45 (CI run: https://github.com/risc0/risc0-rust-examples/actions/runs/4028293123/jobs/6925018354), the risc0_zkvm::guest::sha::digest appears to be broken. I confirmed this and was able to work around it by using a different method, but this one should be fixed (or removed).

**Comment by flaub** [comment]
Can you provide details on what symptoms you are seeing and how reproduce the issue?

**Comment by nategraf** [comment]
Ah, yes. The hash result from the method was incorrect. I did not, today, investigate further into the issue, but I plan to on Monday

**Comment by pdg744** [comment]
Someone sent me a message on discord that I think is related to this issue: 

<img width="543" alt="Screen Shot 2023-01-30 at 8 41 52 AM" src="https://user-images.githubusercontent.com/15272444/215508043-479f1a3d-a1e7-45ec-b772-8e0fddb98098.png">

![image](https://user-images.githubusercontent.com/15272444/215507852-0a9a5e76-bc59-465b-a34f-6c51ed3977d5.png)

**Comment by nategraf** [comment]
So I figured out that there _is_ a bug in this method, with the bit counting for the trailer, although this is not why the only reason why the example was failing. Opened https://github.com/risc0/risc0/pull/357 to address this issue.

**Comment by nategraf** [comment]
> Someone sent me a message on discord that I think is related to this issue:

This issue looks unrelated. If you'd like to direct them to me I'd be happy to help though.

**Comment by flaub** [comment]
> > Someone sent me a message on discord that I think is related to this issue:
> 
> This issue looks unrelated. If you'd like to direct them to me I'd be happy to help though.

We could also have them (or us) file a new issue for this one, but my guess is that this is related to an improper mixing of v0.11 and v0.12 together.
