### ISSUE TITLE
Prover "cannot expand"

### ISSUE THREAD

**Issue by hussein-aitlahcen** [risc0/risc0#360]
Following #358, we now face another issue:
```
Finished release [optimized] target(s) in 5m 48s
     Running `target/release/starter`
Reading prover.
Generating receipt...
thread 'main' panicked at 'impossible: Cannot expand, max po2 of 24 reached.', starter/src/main.rs:10:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Is this because the program is "too big"?

**Comment by SchmErik** [comment]
It's not necessarily the case that the program is "too big" but the program execution including loading the program + executing RISC-V instructions is too long. We have a feature that aims to address this in the near future. For now, you could try reducing your code to see if it can run within 2^24 cycles

**Comment by hussein-aitlahcen** [comment]
@SchmErik thanks, will give it a go with a simpler version :).
