### ISSUE TITLE
Store cache in $XDG_CACHE_HOME instead of $HOME

### ISSUE THREAD

**Issue by mars-risc0** [risc0/risc0#388]
While `.risc0/cache` works fine, it would be nicer to follow the XDG convention, using `$XDG_CACHE_HOME/risc0` if the var is defined, or `$HOME/.cache/risc0` if it is not.

**Comment by flaub** [comment]
We currently use the `home` crate, but we could very easily switch this to https://docs.rs/directories/4.0.1/directories/ instead
