### ISSUE TITLE
memory eqz appears and disappears unexpectedly depending on guest code

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#394]
I've run into an issue where an `eqz` seems to appear/disappear unexpectedly. Here's an example:
```
let buf = [0u8; 32];
unsafe { sys_rand(&buf, buf.len()) }
```
In this code, I have a poorly implemented sys_rand that will cause an `eqz` and this is expected. My implementation of `eqz` writes `buf.len()` bytes of random data to the memory region pointed by `buf`. When I add code that commits an arbitrary message, it runs to completion without the `eqz` being thrown...
```
let buf = [0u8; 32];
unsafe { sys_rand(&buf, buf.len()) }
env::commit(b"hello world") // commit something
```
This code snippet should continue to fail and generate the `eqz`. Here is the output for the first example:
[out.txt](https://github.com/risc0/risc0/files/10799062/out.txt)

Here's the output for the second example: 
[out2.txt](https://github.com/risc0/risc0/files/10799063/out2.txt)

Here's the assembly that I have written:
```
#[inline(always)]
pub unsafe fn sys_rand(buf: &[u8], buf_len: usize) {
    #[cfg(target_os = "zkvm")]
    {
        let mut buf_ptr = buf.as_ptr();
        asm!(
            "ecall",
            in("t0") ecall::SOFTWARE,
            in("a7") nr::SYS_RAND,
            inout("a0") buf_ptr => _,
            in("a1") buf_len,
        );
    }
    #[cfg(not(target_os = "zkvm"))]
    unimplemented!()
}
```

**Comment by SchmErik** [comment]
Note: this isn't a blocker but we should understand what's causing this...

**Comment by SchmErik** [comment]
Here's a branch that exposes this: https://github.com/risc0/risc0/tree/ghost-eqz check the commit message for directions on how to run...

**Comment by SchmErik** [comment]
Here are the objdumps with/without the commit that hides the eqz

[eqz-error-objdump.txt](https://github.com/risc0/risc0/files/10818101/eqz-error-objdump.txt)
[no-eqz-objdump.txt](https://github.com/risc0/risc0/files/10818102/no-eqz-objdump.txt)

**Comment by shkoo** [comment]
As far as I can tell this is what's happening:

When "commit" isn't called, the improperly-written value in `0x02ffff8c` is accessed using the "SW" instruction saving temporary registers in env::finalize:
` 8001e68: 23 20 61 13  	sw	s6, 288(sp)
(It looks like the circuitry for "SW" does a read of the location it's about to overwrite)

When "commit" *is* called, the sw instruction saves to a different memory location, `0x02ffffcc`, and then exits.  So nothing else reads the improperly-written value before the program exits.

So it's purely by chance of stack layout that the "commit" version doesn't trigger an error.

**Comment by SchmErik** [comment]
Makes sense. So it doesn't fail because we don't access the memory region. So it makes sense that this one fails:
```
pub fn main() {
    let buf = [0u8; 32];
    unsafe { sys_rand(buf.as_ptr(), buf.len()) }
    env::commit_slice(&buf);
}
```
@flaub I think this is a non-issue so I'll close. Feel free to reopen if needed. Continuations should detect this because each memory that was written to will be checked after the chunk of code is done. This code snippet
```
let buf = [0u8; 32];
unsafe { sys_rand(&buf, buf.len()) }
```
might be a good failing testcase for continuations!

**Comment by flaub** [comment]
Thanks for getting to the bottom of this :)
