### ISSUE TITLE
`risc0-zkvm::guest::env` does not provide a way to read bytes without knowing the length

### ISSUE THREAD

**Issue by nategraf** [risc0/risc0#402]
The `env::read_slice` API added in https://github.com/risc0/risc0/pull/391 allows for reading slices of bytes and other `Pod` types, which allows for reading of raw input.

However, it is difficult to the entire initial input for the program at once since the `env::read_slice` API requires a length argument, and there is not way to determine how many input elements (e.g. bytes) are available. This makes it difficult to "out-of-the-box" decode a dynamically sized input vector.

**Comment by flaub** [comment]
While we don't yet do this, I'm imagining a scenario where it won't be possible to know how much inputs are available until after doing a request. Right now all inputs are added at the start of the program, but I'd like to be able to support the idea of having an oracle hooked up to the input channel on the host side such that it responds to a request message that comes from the guest.

In the case of a dynamically sized input vector, it seems like you'd want to encode the length of the vector first, then encode the contents itself.

**Comment by nategraf** [comment]
> In the case of a dynamically sized input vector, it seems like you'd want to encode the length of the vector first, then encode the contents itself.

This certainly works, but is less than ideal from a devx perspective if someone wants to "just" write a buffer of bytes once into the guest and receive it on the other side. Without some form of framing, this is likely the best we can do, and we can tell folks to use a wire-format that is compatible with stream decoding.

This came up in Bonsai, where the goal is to pass bytes from a smart contract to the guest. To work with this, the current Bonsai implementation prepends a `u32` length field which the guest is expected to decode first. I opened this issue as a place to track an discussion or decisions we make on whether we can improve on this.

**Comment by flaub** [comment]
I think this is now supported via `env::read_slice`. If it's still an issue let's re-open.
