### ISSUE TITLE
[DevEx] Document how to use Dev Mode feature

### ISSUE THREAD

**Issue by flaub** [risc0/risc0#434]

**Comment by tzerrell** [comment]
Including reviewing what exists

**Comment by 3lkn** [comment]
Prioritizing this as we've had multiple questions on how to use; will also submit details to dev website FAQ.

**Comment by 3lkn** [comment]
https://github.com/risc0/risc0/pull/909 <-- `risc0` README addition
https://github.com/risc0/website/pull/295 <-- FAQ question about dev mode

Note this is for standalone `risc0` projects that don't interact with Bonsai; filing separate issue for defining dev mode for Bonsai-related issues, will leave details there.

**Comment by pdg744** [comment]
Adding a section to the feature flags & an FAQ question is a great start! I agree with Frank's comment on #909 that at some point we should add a `dev mode` page on the website. 

I'm also thinking about where we might want to update docs.rs to make this info more findable... should probably mention dev mode here: https://docs.rs/risc0-zkvm/0.18.0/risc0_zkvm/enum.InnerReceipt.html#variant.Fake -- not sure where else...
