### ISSUE TITLE
Document guest-side logging

### ISSUE THREAD

**Issue by 3lkn** [risc0/risc0#437]

**Comment by flaub** [comment]
Things to note:

1. `env::log`, which works in `no-std` and is implemented via a special syscall.
2. `println!` and `eprintln!` works in `std` environment

I think there's potential work here beyond documentation to make it easier to get diagnostics out of the guest. We should also document env vars that might be needed.

**Comment by tzerrell** [comment]
As @mothran brought up in our verbal discussion, we may also want to give an example with https://docs.rs/tracing-subscriber/latest/tracing_subscriber/
