### ISSUE TITLE
create a binary distribution of the r0vm

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#439]
Building the `risc0` repository requires machines with a lot of memory and processing power. To serve those with lower-powered systems (and for convenience), we should distribute r0vm as a binary. At the very least, we should support macOS and Linux distributions (.deb and/or .rpm?).

It would be great to somehow wrap the starter template so that users running `prover.run()` calls into `r0vm --elf ...` without having to configure their starter templates.

If anyone has other ideas, feel free to chime in!

**Comment by stskeeps** [comment]
WASI or WASM r0vm could be a useful library too

**Comment by SchmErik** [comment]
note, closed because we need to discuss this internally
