### ISSUE TITLE
Show actual cycle count when halt occurs

### ISSUE THREAD

**Issue by pdg744** [risc0/risc0#485]
`prover.cycles` shows the cycle count after padding to the nearest power of 2. 

Would be nice to have a way to show the cycle count before this padding. 

Discord context here: https://discord.com/channels/953703904086994974/975108547589324910/1090541037975523359

**Comment by SchmErik** [comment]
We can now view cycle counts by adding RUST_LOG=info to the cargo command that runs the prover. So something like `RUST_LOG=info cargo run`.
