### ISSUE TITLE
nondeterministic behavior in continuations test

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#554]
The continuations test fails locally and on CI with the following error:
```
R0VM[55083] Busy loop starting!
R0VM[55094] Busy loop complete
thread 'prove::tests::continuation' panicked at 'assertion failed: `(left == right)`
 left: `8`,
 right: `7`', risc0/zkvm/src/prove/tests.rs:219:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test prove::tests::continuation ... FAILED
```
But this test failure occurs intermittently so we need to investigate the source of entropy. This is very likely related to #116 but I'm filing this issue so we can discuss for this specific test case.

**Comment by flaub** [comment]
I think this has been resolved, but if we see it again we can re-open.
