### ISSUE TITLE
Add optional list of "important crates" to inject into the top 1000 crates for validation

### ISSUE THREAD

**Issue by mothran** [risc0/risc0#562]
Currently the [crate-validator](https://github.com/risc0/risc0/tree/main/tools/crates-validator) tool just checks the top 1000 crates. But there are plenty of crates we use in examples, or in common applications that might be useful to also validate.

Add a optional array of crate names to include in the validation list along with the top 1000

Suggested crate classes to start with:
* Serializes (`serde_json`, `bincode`, etc)
* cryptography libraries (`k256`, `tiny-keccak`, etc)
* Ethereum specific (`revm`, `ethabi` etc)

**Comment by carterbrett** [comment]
Idea: Coverage of the top [cryptography crates](https://lib.rs/cryptography) would be cool too

**Comment by flaub** [comment]
There's also been a suggestion to make this a 'service' where users can select their own crate and see how it does.
