### ISSUE TITLE
FFI function signature mismatch

### ISSUE THREAD

**Issue by stskeeps** [risc0/risc0#569]
(found while building for WASM/WASI)

as:
  = note: rust-lld: error: function signature mismatch: risc0_circuit_rv32im_poly_fp
          >>> defined as (i32, i32, i32, i32, i32, i32) -> void in /root/r0/risc0/examples/target/wasm32-wasi/release/deps/sha-430c9cb24ea483af.sha.6a800caa-cgu.8.rcgu.o
          >>> defined as (i32, i32, i32, i32, i32) -> void in /tmp/rustcxKQIy7/librisc0_circuit_rv32im_sys-aa776f50e00ba0c7.rlib(ffi.o)

for 
risc0_circuit_rv32im_poly_fp 

https://github.com/risc0/risc0/blob/main/risc0/circuit/rv32im-sys/src/ffi.rs#L108

should add size_t /* args_len */ here:

https://github.com/risc0/risc0/blob/main/risc0/circuit/rv32im-sys/cxx/ffi.cpp#L123

**Comment by flaub** [comment]
Thanks, good catch!
