### ISSUE TITLE
cargo-risczero fails to build after new cargo-generate / bstr update

### ISSUE THREAD

**Issue by mothran** [risc0/risc0#579]
The following nightly workflow fails while building cargo-generate:
https://github.com/risc0/risc0/actions/runs/5040495627/jobs/9039330965#step:6:195

Upstream tracking issue:
https://github.com/cargo-generate/cargo-generate/issues/942

This currently blocks `cargo install cargo-risczero` installs

Reproduction locally: 
```bash
cd risc0
cargo install --path risc0/cargo-risczero
```

**Comment by yourbuddyconner** [comment]
I am seeing this issue locally on a fresh install, agreed that the cargo-generate upstream is broken

**Comment by mothran** [comment]
cargo-generate pushed a fix in the following commit to handle bstr 1.5: https://github.com/cargo-generate/cargo-generate/commit/7aa00177681596f2aa430c7f4f1000d038162f13

**Comment by flaub** [comment]
Should be fixed as of 0.15.1 (this PR specifically: https://github.com/risc0/risc0/pull/580)
