### ISSUE TITLE
failed building

### ISSUE THREAD

**Issue by wangtsiao** [risc0/risc0#584]
Here are part of the error message.

```
   Compiling evm_in_risc0_methods v0.1.0 (/EvmInRisc0/methods)
evm-in-risc0-guest: Starting build for riscv32im-risc0-zkvm-elfmethods(build)                                                                                                     
evm-in-risc0-guest: error: failed to load manifest for workspace member `/EvmInRisc0/target/debug/build/evm_in_risc0_methods-3b12ab65e5b8ce5e/out/rust-std_fef9a51671a1d244698e454d21cf59182a5e4db9b13814d43c005ab9cea20381/library/sysroot`
evm-in-risc0-guest: 
evm-in-risc0-guest: Caused by:
evm-in-risc0-guest:   failed to read `/EvmInRisc0/target/debug/build/evm_in_risc0_methods-3b12ab65e5b8ce5e/out/rust-std_fef9a51671a1d244698e454d21cf59182a5e4db9b13814d43c005ab9cea20381/library/sysroot/Cargo.toml`
evm-in-risc0-guest: 
evm-in-risc0-guest: Caused by:
evm-in-risc0-guest:   No such file or directory (os error 2)
```

I narrowed the error to
```
'sysroot/Cargo.toml' does not exists at 'rust-std'
```

**Comment by wangtsiao** [comment]
For reproducing the error, here is the [repository](https://github.com/wangtsiao/zkevm-risc0/).

**Comment by flaub** [comment]
This line is incompatbile with `risc0-zkvm = 0.15`:
```
risc0-zkvm-guest = "0.11.1"
```

To get the guest functionality, use this line:

```
risc0-zkvm = { version = 0.15, default-features = false, features = ["std"] }
```

Or remove the `std` feature if you don't need or want to use the rust stdlib.

**Comment by wangtsiao** [comment]
@flaub Thank you, I changed the [risc0-zkvm](https://github.com/wangtsiao/zkevm-risc0/commit/02e75c9298649a6f582c646db44a1e233678e914).

But it still has the same error.

**Comment by mothran** [comment]
@wangtsiao it appears your missing the `rust-toolchain.toml` (example: https://github.com/risc0/risc0/blob/main/templates/rust-starter/rust-toolchain) file in the root which might be causing some of the issue. I highly recommend using the `cargo-risczero` tool: https://crates.io/crates/cargo-risczero to generate new projects because it will setup all the packages / rust correctly.

**Comment by wangtsiao** [comment]
> @wangtsiao it appears you're missing the `rust-toolchain.toml` (example: https://github.com/risc0/risc0/blob/main/templates/rust-starter/rust-toolchain) file in the root which might be causing some of the issue. I highly recommend using the `cargo-risczero` tool: https://crates.io/crates/cargo-risczero to generate new projects because it will setup all the packages / rust correctly.

Thank you, I recreate the project with `cargo-risczero`, but it didn't go well and still didn't compile successfully. Here is the new error
```
error[E0432]: unresolved imports `risc0_zkvm::Executor`, `risc0_zkvm::ExecutorEnv`
 --> host/src/main.rs:6:5
  |
6 |     Executor, ExecutorEnv,
  |     ^^^^^^^^  ^^^^^^^^^^^ no `ExecutorEnv` in the root
  |     |
  |     no `Executor` in the root
```

here is the new [repository](https://github.com/wangtsiao/zkevm-risc0/tree/cbee24e21f745672628e70a8288e7399e55fa981).

**Comment by flaub** [comment]
The host side needs to have the `prove` feature enabled, so you can use this on the host side:

```
risc0-zkvm = "0.15"
```
