### ISSUE TITLE
Support Traditional Rust Build?

### ISSUE THREAD

**Issue by zicklag** [risc0/risc0#59]
I was just trying to build risc0 and unfortunately ran into issues because I'm behind an HTTP proxy that requires authentication and has a custom HTTPS certificate, and Java, which is apparently what bazel is using to download files, **really** doesn't like proxies.

I've never gotten Java to successfully go through my proxy. :confused: 

Anyway, that's not really your fault or anything you can do about it, but I was also wondering whether or not you would be open to supporting alternative build systems, such as would allow you to add the Rust crate to a normal Rust project and have it built without requiring Bazel to be installed.

Usually this is done in the Rust `build.rs` script, which will compile the C++ automatically and setup the linker so that the Rust user doesn't really have to think about the C++, other than making sure they have a C++ compiler installed.

I could probably setup a separate git Repo that would add this one as a submodule and contain the build scripts if it wasn't something you wanted to worry about integrating into this repo, but I wanted to see how you felt about it.

----

Somewhat related I was also wondering if you had any warnings for me if I attempted to do a pure Rust port. :)

Rust is my favorite language and the most-used in projects I'm investing in, and I noticed that this project wasn't massive on lines of code. Only 6.3k lines of C++ code, which is awesome that you've been able to keep the codebase so small!

Also, I'm thinking from the perspective of needing to compile to WASM, and I'm not sure how well compiling a hybrid C++/Rust project will work when I need to target WASM. I'm not sure if that requires building the C++ to WASM and then the Rust to WASM and linking the two WASM modules? ( I think that's experimentally supported by something, but I can't remember where I saw that. )

----

Anyway, I'm just getting into a closer investigation of the project and I'm not sure if I'll actually have time to mess around much longer or if I'll get to using it for anything, but I really appreciate your time!

**Comment by flaub** [comment]
Fear not, this is in the works! We also share these concerns and want to make the developer experience as seamless and friction-less as possible.

However, to get there will take a number of steps:
1. Add a new target-triple to rust-lang: `riscv32im-risc0-zkvm-elf`. I've been reasonable progress on this front. The reason for this is so that we can use `std` in zkvm-guest code.
2. Make the C++ code be usable as a binary (rather than as a library as it is today).
3. Make everything cargo buildable.

We're also looking at making the prover be pure-rust, but don't have a firm timeline on that yet. Contributions would be very welcome!

**Comment by zicklag** [comment]
Awesome, that's really promising, then! It sounds like we're on the same page. :smile:

> Add a new target-triple to rust-lang: riscv32im-risc0-zkvm-elf. I've made reasonable progress on this front. The reason for this is so that we can use std in zkvm-guest code.

That makes sense and sounds like it might _really_ help the user experience when writing Rust guest code.

It looks like you've got a plan for what needs to happen, too which is great.

> Contributions would be very welcome!

There's some really slim chances I'll have time to start messing around with a Rust port, but you never know what might happen.

For now I'll just start at `core` and start seeing about re-writing it in Rust and see where I get.

I'd like to understand more about how STARKs work under-the-hood anyway, so I might be doing that while also taking some looks through [Anatomy of a STARK](https://aszepieniec.github.io/stark-anatomy/).

**Comment by jbruestle** [comment]
FYI, we just got a pure rust version of the verifier working, we plan to open source it shortly (In the next day few days).

**Comment by flaub** [comment]
Pure-rust verifier: https://github.com/risc0/risc0/pull/75

**Comment by flaub** [comment]
#95 gets us one step closer.

**Comment by flaub** [comment]
I believe this is now resolved. Checkout our "out of tree" examples for how to setup your project to use rust/cargo tooling (without any bazel). 

* https://github.com/risc0/risc0-rust-starter
* https://github.com/risc0/battleship-example

**Comment by zicklag** [comment]
That's awesome, I'll check it out. Great work!
