### ISSUE TITLE
<use std:: sync:: atomic:: AtomicU64> AND <use std:: sync:: atomic:: AtomicU8>

### ISSUE THREAD

**Issue by Guangguang888** [risc0/risc0#602]
In the host, you can 《use std:: sync:: atomic:: AtomicU64》; And 《use std:: sync:: atomic:: AtomicI64》;. In a guest, only 《std:: sync:: atomic:: AtomicU8》 can be used; And 《use std:: sync:: atomic:: AtomicI8》;    Does this mean that zkvm only supports 《-2 ^ 7 to 2 ^ 7-1》, and does not support 《-2 ^ 63 to 2 ^ 63-1》?

**Comment by SchmErik** [comment]
the zkVM implements riscv32im so each register can hold 32 bits. https://github.com/riscv/riscv-isa-manual/releases/download/Ratified-IMAFDQC/riscv-spec-20191213.pdf

Atomics imply that the architecture may do some sort of preemption. However, our circuit doesn't support preemption and the code is executed only on a single thread of execution. This means that all instructions are atomic in that they cannot be interrupted. Hope that helps! Let me know if you have other questions

**Comment by SchmErik** [comment]
closing, as there's nothing here to fix
