### ISSUE TITLE
the lang item is first defined in crate `std` (which `serde` depends on)

### ISSUE THREAD

**Issue by Guangguang888** [risc0/risc0#609]
When I introduce dependencies in the cargo. toml of Guet, sometimes this error occurs. What is the reason for this. 
![image](https://github.com/risc0/risc0/assets/97269757/48438444-0b42-49e4-be81-37f7d76be2dd)
this is cargo.toml:  
risc0-zkvm = { version = "0.15.2", default-features = false }
seal_fhe = { version = "0.7.0", default-features = false }

If the second line is not added, no error will be reported.

**Comment by flaub** [comment]
This kind of error usually means that some other dependency requires the use of `std`. To resolve this, you can use this in your guest `Cargo.toml`:

```
risc0-zkvm = { version = "0.15.2", default-features = false, features = ["std"] }
```

Additionally, remove the `#![no_std]` attribute from the guest code.

**Comment by flaub** [comment]
If this doesn't work, please re-open this issue with additional context.
