### ISSUE TITLE
Optionally redirect guest stderr / stdout to file

### ISSUE THREAD

**Issue by mothran** [risc0/risc0#610]
In order to redirect the guest output to a file from the executor we should provide optional arguments to capture all guest logs on stdout / stderr and redirect them to a file.

**Comment by SchmErik** [comment]
@mothran by guest logs, do you mean `env::log(...)`?

**Comment by mothran** [comment]
> @mothran by guest logs, do you mean `env::log(...)`?

All stdout / stderr from the guest.

**Comment by SchmErik** [comment]
@flaub I think you had mentioned how to do this previously when we were initially talking about binary distributions.. Do you have any thoughts on how we would go about doing this?

**Comment by flaub** [comment]
Capturing stdout and stderr are already possible, what's missing is #1028, closing in favor.
