### ISSUE TITLE
merge receipts representing sessions into a sinlge session receipt type

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#620]
As of #616, we have two kinds of receipts: `FlatSessionReceipt` and `SessionRollupReceipt`. The verification uses different data structures (`ReceiptMetaData` vs `ReceiptMeta`) and a duplicated `SystemState` struct that could be cleaned up. Once these things are done and both verify functions match semantically, we can merge both receipts into a single SessionReceipt type

**Comment by flaub** [comment]
We have a solution in 0.16, but it breaks no_std/wasm targets. This PR is meant to deal with that issue: #703
