### ISSUE TITLE
Run Doom on zkVM

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#621]
With continuations, we should be able to run something like this:
https://github.com/cristicbz/rust-doom

We'll likely need to figure out I/O and graphics but this should be fun

**Comment by shuklaayush** [comment]
I'd like to work on this. How do I make this happen?

**Comment by SchmErik** [comment]
You can do this by porting the codebase as a guest code using our starter template and replace all of the graphics/audio/I/O calls to a special syscall handler similar to our [waldo example](https://github.com/risc0/risc0/tree/main/examples/waldo). You could start by porting each module used in the project (wad, engine, game, and math). Hope this is helpful!

**Comment by pdg744** [comment]
I think what we really want here is a proof of [speedrun](https://doomwiki.org/wiki/Speedrun). The proof would demonstrate a speedrun is possible in XYZ seconds, without disclosing the in-game actions necessary to achieve this result. 

- The zkvm guest receives a [demo](https://doomwiki.org/wiki/Demo) file as input.
- The guest confirms the validity of the demo file
- The guest commits the elapsed time to the journal.

**Comment by felipeargento** [comment]
You might want to check out the [cartesi-doom](https://github.com/edubart/cartesi-doom-example) example built by edubart. The cartesi machine is also based on RISC-V, and from what I remember, they tackled similar challenges related to graphics and I/O. The implementation might provide some insights!

**Comment by SchmErik** [comment]
this has been done https://github.com/risc0/demos/tree/main/zkdoom
closing.
