### ISSUE TITLE
Trivial Factors proving fails when compiled using metal feature

### ISSUE THREAD

**Issue by jcbdev** [risc0/risc0#622]
I have a project set up with the trivial factors example all working building and running correctly on cpu.

If I add the metal feature I then get the following panic (ImageVerificationError):
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ImageVerificationError'
```

**Comment by SchmErik** [comment]
@jcbdev could you give me the link to the tutorial you followed? I tried doing something similar on my end and it ended up working. I'd be curious to try what you tried on my side to reproduce the error that you got

**Comment by tzerrell** [comment]
I was not able to reproduce this insofar as running
```
cargo test -F metal
```
from the `examples/factors` directory passes. Does this work for you?

**Comment by flaub** [comment]
@jcbdev I'm curious what hardware you're trying this on. We've tested on M1 and M2 macs

**Comment by jcbdev** [comment]
I am on an M2 mac.  I started a new project with the starter template and then followed the tutorial.

The only difference from the normal starter template was I converted it to a lib and imported into another cargo app 🤔

**Comment by flaub** [comment]
@jcbdev Is this still happening with the latest release? Do you an repo you can share that has this behavior?
