### ISSUE TITLE
risc0-circuit-rv32im-sys is not compiling

### ISSUE THREAD

**Issue by onurinanc** [risc0/risc0#628]
I'm trying to do factors example inside https://github.com/risc0/risc0/tree/main/examples/factors. However, 275/285 which, risc0-circuit-rv32im-sys, is not compiling

`    Building [=======================> ] 275/285: risc0-circuit-rv32im-sys(...`

**Comment by flaub** [comment]
This crate may take a very long time to compile, in the range of 10-30 minutes depending on the machine you're doing the build on.

**Comment by onurinanc** [comment]
Will this be just for the one time compilation for the every project that we want to build and run?

**Comment by flaub** [comment]
This will occur once per rust workspace. So if you have multiple projects in a single workspace, only one time. In the future, we plan to move to a pre-built binary distribution model to deal with this and other issues.

I'll close this but if you still have issues, please feel free to open again.
