### ISSUE TITLE
no matching package named "methods" found

### ISSUE THREAD

**Issue by onurinanc** [risc0/risc0#629]
`error: no matching package named `methods` found
location searched: /home/onurinanc/risczero/factors/methods
required by package `host v0.1.0 (/home/onurinanc/risczero/factors/host)`

I'm having this error when I ran cargo run --release in here https://github.com/risc0/risc0/tree/main/examples/factors#step-4-build-and-run-the-project

**Comment by onurinanc** [comment]
You should also add the following to the step4:
- In host/Cargo.toml, you should change the dependency name from methods to factors-methods

**Comment by flaub** [comment]
Is this still occurring with the latest release? @tzerrell @pdg744 Any ideas here?

**Comment by lvertiz4** [comment]
I got tripped up on this while trying to run the tutorial for version 0.17.0 . I'll report back if there are any additional missing pieces that remain to be added to the README in the 'Factors' tutorial.

**Comment by tzerrell** [comment]
This should be fixed with https://github.com/risc0/risc0/pull/793 -- thanks @winor30! Feel free to reopen if you run into this again or hit further related problems.
