### ISSUE TITLE
Add support for CID

### ISSUE THREAD

**Issue by omurovec** [risc0/risc0#655]
# Overview
It could be very helpful to support [CID](https://github.com/multiformats/cid) for proving data exists at a given cid on IPFS. This could be especially helpful on-chain where a lot of data is stored on ipfs but inaccessible in the EVM.

# Implementation
The implementation could be very similar to the current sha implementation, instead using the [CID crate](https://crates.io/crates/cid). CIDs could also have use cases outside of ipfs which is why it might be best to implement for the zkVM directly and create an ipfs example.

**Comment by omurovec** [comment]
On second thought, this may not be appropriate to add to the zkVM as it is non-essential and it would be better to leave it to users to implement for themselves

**Comment by flaub** [comment]
Although adding an IPFS demo/example would be very neat!
