### ISSUE TITLE
zkVM: make it easier to get random numbers in guest

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#656]
Right now, the zkVM exposes random numbers in guest by exposing an implementation of `getrandom()`if a guest crate needs requires it. We may want to simplify this by perhaps adding something like `env::random()`.

**Comment by carterbrett** [comment]
Blocked on good questions about the approach. @heavypackets is leading RFC effort on this.

**Comment by carterbrett** [comment]
Closing in lieu of approach described in the Randomness RFC.
