### ISSUE TITLE
Step 7 in Factors README has erroneous code

### ISSUE THREAD

**Issue by pdg744** [risc0/risc0#659]
## The problem
Step 7 of the factors readme shows the following code snippet, which contains a broken use of `get_journal()`. See Discord discussion this morning for context. 
https://discord.com/channels/953703904086994974/975108547589324910/1123558864072224813

AFAIK the current syntax is `receipt.journal`, but not quite sure whether this is just a one-off code snippet that needs to be fixed or if there's some mis-alignment between `main`/`0.15.3` and this tutorial. 

Relatedly: I wonder whether it's possible to write github urls that point to the latest release rather than pointing to main...

 ``` 
  use factors_methods::{MULTIPLY_ELF, MULTIPLY_ID};
    use risc0_zkvm::{
      serde::{from_slice, to_vec},
      Executor, ExecutorEnv,
    };

    let a: u64 = 17;
    let b: u64 = 23;

    let env = ExecutorEnv::builder()
    // Send a & b to the guest
    .add_input(&to_vec(&a).unwrap())
    .add_input(&to_vec(&b).unwrap())
    .build()
    .unwrap();

    let mut exec = Executor::from_elf(env, MULTIPLY_ELF).unwrap();
    let session = exec.run().unwrap();

    let receipt = session.prove().unwrap();
    receipt.verify(MULTIPLY_ID.into()).unwrap();

    // Extract journal of receipt (i.e. output c, where c = a * b)
    let c: u64 = from_slice(&receipt.get_journal()).unwrap();

    // Print an assertion
    println!("Hello, world! I know the factors of {}, and I can prove it!", c);
```

**Comment by SchmErik** [comment]
> Step 7 of the factors readme shows the following code snippet, which contains a broken use of `get_journal()`. See Discord discussion this morning for context. https://discord.com/channels/953703904086994974/975108547589324910/1123558864072224813
> 
> AFAIK the current syntax is `receipt.journal`, but not quite sure whether this is just a one-off code snippet that needs to be fixed or if there's some mis-alignment between `main`/`0.15.3` and this tutorial.

So 0.15.3 uses `receipt.journal` but the current main uses `receipt.get_journal()` but it'll be changed back to `receipt.journal` in the near future. While zkVM API's are getting more stable, I think it's better to point to a released version of the docs from our website.

> 
> Relatedly: I wonder whether it's possible to write github urls that point to the latest release rather than pointing to main...

So we could use this for now - 
https://github.com/risc0/risc0/tree/release-0.15/examples/factors
This is where the latest releases are happening for now. I think the branch name will change once we cut a release for 0.16

**Comment by flaub** [comment]
The changes on main were incompatible just before 0.16 was released but I think we're all good now. Feel free to re-open if there's still an issue.
