### ISSUE TITLE
The README Logo is Invisible on GitHub Light Theme

### ISSUE THREAD

**Issue by zicklag** [risc0/risc0#66]
Just noticed that the logo is invisible on the GitHub light theme. Not a huge deal, because you can't see it at all, but might be something to fix sometime.

![image](https://user-images.githubusercontent.com/25393315/163690859-85db49aa-0087-4f0c-86ab-826e0493e946.png)

**Comment by rlukata** [comment]
I honestly would have never noticed, literally first thing I do if something is blasting with white brightness is find the dark theme option. Thank you for noticing and opening an issue.

**Comment by zicklag** [comment]
Awesome, that worked great! I didn't realize there was a good way to do different images for light and dark.
