### ISSUE TITLE
Bonsai proving with new template project

### ISSUE THREAD

**Issue by carterbrett** [risc0/risc0#671]
### Objective
We want devs who start a new project with `cargo-risczero new` to be able to do their proving with Bonsai by setting a API key, API url, and a flag as environment variables, the same way that it's done with the Bonsai Foundry Template.

### References
Code example of how this is done in the Foundry template: [https://github.com/risc0/bonsai-foundry-template/blob/main/.github/workflows/test.yml#L72](https://github.com/risc0/bonsai-foundry-template/blob/main/.github/workflows/test.yml#L72 )

**Comment by mothran** [comment]
https://github.com/risc0/risc0/pull/677
