### ISSUE TITLE
ExecutorEnvBuilderErr missing Error impl

### ISSUE THREAD

**Issue by mothran** [risc0/risc0#681]
The `ExecutorEnvBuilderErr` type at https://github.com/risc0/risc0/blob/b35e1faa37fb4b60cf8dd849cf46b14d1713c881/risc0/zkvm/src/exec/env.rs#L117 
does not derive / impl the `Error` trait so when used with `anyhow` it fails to compile.

```
40 |     let env = ExecutorEnv::builder().add_input(&input).build()?;
   |                                                               ^ the trait `std::error::Error` is not implemented for `risc0_zkvm::exec::env::ExecutorEnvBuilderErr`
```

I would recommend using `thiserror` to quickly derive the Error impl for this enum.

**Comment by SchmErik** [comment]
fixed by #684
