### ISSUE TITLE
cargo run --release fails on factors example

### ISSUE THREAD

**Issue by rezahsnz** [risc0/risc0#706]
My pc:
cpu: i7 5500u
ram: 16gb ddr3
os: ubuntu 18.04

I'm trying to run the factors example on my pc but it fails with the following error messages at end of [step 4](https://github.com/risc0/risc0/tree/v0.16.0/examples/factors#step-4-build-and-run-the-project). Here's the log:
[log.txt](https://github.com/risc0/risc0/files/12070718/log.txt)

```
$ cargo run --release
Compiling risc0-circuit-rv32im-sys v0.16.1
The following warnings were emitted during compilation:

warning: c++: internal compiler error: Killed (program cc1plus)
warning: Please submit a full bug report,
warning: with preprocessed source if appropriate.
warning: See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.

error: failed to run custom build command for `risc0-circuit-rv32im-sys v0.16.1`

Caused by:
  process didn't exit successfully: `-path-/factors/target/release/build/risc0-circuit-rv32im-sys-c8001a6566e0215a/build-script-build` (exit status: 1)
```

**Comment by rezahsnz** [comment]
The same kind of error occurs when I try to benchmark my pc within the risc0 package.

**Comment by flaub** [comment]
The `poly_fp.cpp` file is very intensive for most compilers and we've seen similar "internal compiler error" (ICE) with older compilers. It's also possible that the compiler is running out of RAM. Here are a few workarounds I can offer:

* Use a newer version of gcc
* Install clang and use it with: `export CC=clang CXX=clang++`
* Build on a machine with more RAM

In the future, we plan to have prebuilt binaries that will be published for cases like this.

**Comment by rezahsnz** [comment]
Yes, it was a ram issue! Seems that minimum ram is > 16gb and a safe bet would be 24-32gb.
