### ISSUE TITLE
Consider using paths-filter github action

### ISSUE THREAD

**Issue by flaub** [risc0/risc0#734]
https://github.com/dorny/paths-filter

This can be used to filter which jobs run from which directory changes.

**Comment by imdaisyadams** [comment]
I like this idea, that way we don't run all jobs all the time

**Comment by morgangibbs87** [comment]
Project was forked into risc0 and can now be referenced and utilized.

**Comment by morgangibbs87** [comment]
Due to conflicting rules from current paths in workflow causing jobs to freeze, this has been disabled:


![Image](https://github.com/risc0/risc0/assets/133707571/966971ab-18bd-429e-a36f-21fbbc4aa565)


It will need to be re-enabled once this is set up and working.

**Comment by flaub** [comment]
I think this is the right approach: https://github.com/getsentry/sentry/blob/2ebe01feab863d89aa7564e6d243b6d80c230ddc/.github/workflows/backend.yml#L20

**Comment by morgangibbs87** [comment]
Frank fixed this in https://github.com/risc0/risc0/pull/1103
