### ISSUE TITLE
Guest builds fail due to `cc` crate 1.0.80

### ISSUE THREAD

**Issue by mothran** [risc0/risc0#754]
After the release of `cc` crate 1.0.80 the zkvm guest build fails with the following errors:

```
method_name: error[E0152]: duplicate lang item in crate `core` (which `rustc_std_workspace_core` depends on): `sized`.
method_name:   |
method_name:   = note: the lang item is first defined in crate `core` (which `std` depends on)
method_name:   = note: first definition in `core` loaded from /home/user/.rustup/toolchains/nightly-2023-03-06-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-05898138a596088a.rlib
method_name:   = note: second definition in `core` loaded from /home/user/tmp/cc-bug/target/riscv-guest/release/deps/libcore-d6bc9e683b556e25.rmeta
<snip>
```

## Workaround:

Place the following config:
```toml
[patch.crates-io]
cc = { git = "https://github.com/rust-lang/cc-rs", rev = "e5bbdfa" }
```
into either:
* Your current rust workspace root `.cargo/config.toml`
* Or system wide at `~/.cargo/config.toml`

## Origin

Appears to be related to the following commit https://github.com/rust-lang/cc-rs/commit/17c8858efbeec6094c21973e3d2e9773916b6aa2 and respective PR in `cc-rs`: https://github.com/rust-lang/cc-rs/pull/780

`cc` is not in the default guest cargo depenendency tree but is in the `build-std` build tree so its most likely a mix up within our `std` building.

**Comment by 0xfuturistic** [comment]
same. thanks for the workaround -- it worked.

**Comment by Amosel** [comment]
Super appreciated!

**Comment by jiayaoqijia** [comment]
@Amosel Can you also apply this hot fix to risc0 main repo? Thanks.

**Comment by flaub** [comment]
This has been applied in https://github.com/risc0/risc0/pull/757
