### ISSUE TITLE
Sending code or docker container to verifier

### ISSUE THREAD

**Issue by amusgrave-via** [risc0/risc0#755]
Due to issues with deterministic builds, it is currently not clear how to allow a verifier to be certain that an image ID comes from the stated guest code. Our attempts to serialize a receipt, send it to another device, and have that device verify it with the same risc0 project which they have compiled locally have all failed.

One approach which was suggested [here](https://github.com/risc0/risc0/issues/116#issuecomment-1403810479) is to build the project in a docker container and send the container for another party to verify. However, we have also not succeeded in running our risc0 projects (which run correctly on desktop) in docker containers. The most common error trace we get is shown below:

```   Compiling factors-methods v0.1.0 (/factors/methods)
error: failed to run custom build command for `factors-methods v0.1.0 (/factors/methods)

Caused by:
  process didn't exit successfully: `/factors/target/debug/build/factors-methods-7b921c936b2e62ef/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)
  --- stdout
  Standard library /factors/target/debug/build/factors-methods-3c8cc1556b2bae16/out/rust-std_ad062567ca92a9b48981bf6d4ac3375b88abc750249689321f6ab3bbc996d11d does not exist; downloading 
```

Would it be possible to provide an example of how another party is able to verify a receipt from guest code? If the solution involves a docker container, than a Dockerfile / project which builds successfully would be very helpful.

**Comment by flaub** [comment]
Related to #116
