### ISSUE TITLE
Bincode Deserialization Error

### ISSUE THREAD

**Issue by orkunkilic** [risc0/risc0#766]
I am facing an error while my prover is trying to deserialize the bincode that it retrieved from Bonsai API.

I also get the bincode manually using Swagger UI and tried to deserialize it into Receipt in other program but still got the error. Creating SNARK on Swagger is working fine, so I couldn't find where the error is. I guess Receipt struct in v0.16.1 is different than the Receipt struct in Bonsai but I am not sure.

```
thread 'main' panicked at 'called "Result::unwrap()" on an "Err" value: Io(Kind(UnexpectedEof))', host/src/main.rs:85:56
```

Is this a known bug?

**Comment by capossele** [comment]
What concrete struct are you using for the deserialisation?
I think 0.16.1 uses `SessionReceipt` https://github.com/risc0/risc0/blob/0d02111b2f84a53cf6198a0064086b281ed0f749/risc0/zkvm/src/receipt.rs#L162

**Comment by flaub** [comment]
If you're still having this issue, please re-open, closing for now.
