### ISSUE TITLE
template: use workspaces for risc0 dependencies

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#770]
The current template uses many `Cargo.toml` files containing risc0 dependencies such as `risc0-zkvm` and `risc0-build`. Often times, when I try to update my dependency, i forget to update all risc0 dependencies across the multiple cargo.toml files and end up with a build error that's difficult to understand. To make this easier, the template can generate the project template's root `Cargo.toml` with risc0 dependencies as workspace dependencies so that the user can change the version of risc0 dependencies from one file

**Comment by flaub** [comment]
I don't think this is possible since the guest and host workspaces must remain independent.
