### ISSUE TITLE
zkVM: make r0vm more modular (step 1)

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#774]
A good place to start in figuring out our versioning story is to get bonsai to call into r0vm to do do execution and proving.

In order to get this to work, we can do something similar to remote proving: when using the API, we can set an environment variable to get the zkVM API's to call into r0vm. At the time of writing, r0vm only allows generating proofs from elf + inputs. We need to allow r0vm to do executor only, proving only, and enable r0vm to pause and continue (in order to flush segments so that r0vm does not completely deplete memory).

As a first step, we can use an environment variable called `RISC0_R0VM` (or some other name). When this variable is set, `prover.prove_elf(...)` will call into the r0vm binary in order to generate the receipt.

**Comment by carterbrett** [comment]
Closing this along with #745 and #746 as @flaub has picked this up.
