### ISSUE TITLE
zkVM: make r0vm more modular (step 3)

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#776]
A good place to start in figuring out our versioning story is to get bonsai to call into r0vm to do do execution and proving.

In order to get this to work, we can do something similar to remote proving: when using the API, we can set an environment variable to get the zkVM API's to call into r0vm. At the time of writing, r0vm only allows generating proofs from elf + inputs. We need to allow r0vm to do executor only, proving only, and enable r0vm to pause and continue (in order to flush segments so that r0vm does not completely deplete memory).

As the third step, we need to enable r0vm to pause after each segment is generated from the executor. This might require refactoring the current zkvm API. The reasoning behind this is to prevent the machine running `r0vm --executor-only` to flush segments from memory so that it does not run out of memory. We need some sort of IPC for this and the segment needs to be stored in RAM.

**Comment by carterbrett** [comment]
Closing see https://github.com/risc0/risc0/issues/774#issuecomment-1682708316
