### ISSUE TITLE
zkVM: create a separate r0vm-like program for recursive proving

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#777]
relates to [insert references to other issues here]

As a part of the versioning story, Bonsai needs to use a binary executable in order to do succinct roll ups. The recursive prover lies in a private repo and (because r0vm lies in the public repo) r0vm cannot be used. We need a separate program similar to r0vm that runs the recursive prover.

**Comment by carterbrett** [comment]
Closing, see https://github.com/risc0/risc0/issues/774#issuecomment-1682708316
