### ISSUE TITLE
Create installation page

### ISSUE THREAD

**Issue by pdg744** [risc0/risc0#796]
- [ ] Create an installation page that describes how to install `cargo risczero` and the toolchain
- [ ] Update Quick Start section in examples to point to installation page
- [ ] Include instructions for how to check whether the toolchain is installed, and what version

**Comment by flaub** [comment]
FYI, if you do `- [ ]` instead of just `[ ]` github will treat that as a checklist: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#creating-task-lists

**Comment by pdg744** [comment]
I wonder if a stand-alone installation page is preferable to a clearly delineated installation step as part of a Quick Start guide? 

I think [this page](https://dev.risczero.com/zkvm/quickstart#1-install-the-risc-zero-toolchain) may provide what we're looking for in an `Installation` page.

**Comment by tzerrell** [comment]
I think we should have a standalone installation page. Whether it makes sense to point everything to that page is a bit more of an open question to me -- it helps with maintenance, but I think the user experience can be worse (have to click too many things). But, for people coming from e.g. googling "install risczero" having a dedicated page is good, and there's nothing preventing us from keeping instructions on other pages (perhaps turning "install" into a link as well for the curious).

Right now risc0/website#286 does just this first part (of creating a separate install page)

**Comment by flaub** [comment]
I think we'll need to make sure this stays in sync with or we have a link to: https://github.com/risc0/risc0/blob/main/risc0/cargo-risczero/README.md#install

**Comment by tzerrell** [comment]
> I think we'll need to make sure this stays in sync with or we have a link to: https://github.com/risc0/risc0/blob/main/risc0/cargo-risczero/README.md#install

I've linked this page in the latest revision of risc0/website#286, and I used a versioned link, which should prompt us to review if these got out of sync at least as often as we release.
