### ISSUE TITLE
Failure to split a computation consisting in iterating calls to sha256

### ISSUE THREAD

**Issue by igarnier** [risc0/risc0#820]
One can get the following error when running a long computation iterating calls to sha256:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Cannot expand, max po2 of 20 reached.', host/src/benches/iter_sha2.rs:82:89
```
This was observed on 0.17.0.

Steps to reproduce:
- Clone this branch: https://github.com/igarnier/zk-benchmarking/tree/iter-sha2-failure
- `cd risczero`
- `cargo b -r`
- `target/release/host --out dummy.csv iter-sha2`

The guest code is there: https://github.com/igarnier/zk-benchmarking/blob/iter-sha2-failure/risczero/methods/guest/src/bin/iter_sha2.rs

The error was triggered for `num_iter = 10_000` (this is an upper bound, didn't try to bisect).

**Comment by SchmErik** [comment]
From reading the trace log, it doesn't look like this is setting the `is_halted` to `true` at the cycle count for the split. I expect to see this message: `log::info!("SPLIT[{cycle}]> pc: 0x{pc:08x}");`
