### ISSUE TITLE
`risc0_binfmt` breaks the `no_std` support 

### ISSUE THREAD

**Issue by SkymanOne** [risc0/risc0#833]
The #725 PR introduced some refactoring to the crate system of `risc0_zkvm` crate. 
It also explicitly replaced `alloc` versions of data structures with the `std` ones:
https://github.com/risc0/risc0/blob/9b2d494689b54fbbe51962276ac557f88c8b0746/risc0/binfmt/src/elf.rs#L15 

Because these imports are not feature-gated and `risc0_zkvm` uses `risc0_binfmt` by default for verification:
https://github.com/risc0/risc0/blob/9b2d494689b54fbbe51962276ac557f88c8b0746/risc0/zkvm/Cargo.toml#L54

This essentially breaks earlier support `risc0_zkvm` for `no_std` environment.

I am happy to work on the fix PR, if possible.

**Comment by flaub** [comment]
#857 should fix this, but I don't have a good test for it yet. @SkymanOne We'd be happy to add another test to ensure this doesn't break in the future.
