### ISSUE TITLE
Write RFC for examples repo

### ISSUE THREAD

**Issue by 3lkn** [risc0/risc0#841]
There's a lot to spec out for examples process and requirements. To keep this modular, starting with the topic of standardization (and the process of maintaining it).

Standardization problem:
While the examples directory in the `risc0` repository contains examples that are necessarily up to date in terms of `risc0` core compatibility, there's a lack of consistency and standardization. The examples are often out of sync with each other and with the existing default `cargo risczero` template.

This proposal will detail when and where standardization should take place across examples and with our template. At a high level, I will propose clarifying which of our examples are 'showcase' and which are 'cookbook' and treat them slightly differently. For showcase pieces with instructional elements, will suggest treating these elements more cookbook like. The technical part of the RFC details which bits should always be in alignment with template (and each other)
and which only need to be in alignment for cookbook-like sections.

Process includes communicating the purpose of examples to support above requirements, and a brief proposed process that aligned with the version release schedule around combing through existing examples for needed updates.

**Comment by carterbrett** [comment]
This blocks https://github.com/risc0/risc0/issues/807 as we need to align on the approach prior to updating the examples themselves
