### ISSUE TITLE
The dev ex of the `add_input`

### ISSUE THREAD

**Issue by pepyakin** [risc0/risc0#845]
https://docs.rs/risc0-zkvm/latest/risc0_zkvm/struct.ExecutorEnvBuilder.html#method.add_input

I hope the problem is described by the two interactions below:

> The add_input API is not intuitive. Imagine you need to pass a Vec<u8> via add_input and env::read it in the guest. I would expect it would work if I just pass a raw vector. However, I have to always go through to_vec. This part is surprising  and the docs don't clarify nor have an example. 

> However, imagine that you are a developer that wants to start asap, with the starter template. You have a byte buffer, and assume that since it's a byte buffer no special serialization is needed, since in a lot of different places this is how it usually work. It doesn't work with some cryptic error (such are the serialization/deserialization errors). You go to the documentation, don't see any note on this, but see the example, which kinda doesn't tell you much to fix the wrong mental model, if anything it only confirms it: well, I have a byte vec, why do I need to to_vec it?
i think the signature with the Pod give a hint that something is fishy, but once again, you are an eager developer who wants to get the hands dirty!

**Comment by pdg744** [comment]
Thanks for flagging this!
