### ISSUE TITLE
0.18 Document reproducible builds / `cargo risczero build` changes

### ISSUE THREAD

**Issue by heavypackets** [risc0/risc0#867]
Update documentation on:

- How Image ID is created and what it promises (and does not promise)
- RISC Zero's definition of reproducible builds are what are our guarantees
- Changes to `cargo risczero build` given new docker based process

**Comment by tzerrell** [comment]
> Changes to `cargo risczero build` given new docker based process

There was no `cargo risczero build` command in 0.17, so this will look like a "new command introduction" rather than "changed command". Sorry, I gave an ambiguous title.
