### ISSUE TITLE
Create DEV_MODE documentation

### ISSUE THREAD

**Issue by 3lkn** [risc0/risc0#888]
Write user-facing documentation describing developer mode and its options, failsafes, and potential pitfalls.

[Paul]: This looks like a duplicate with https://github.com/risc0/risc0/issues/434

**Comment by pdg744** [comment]
This is marked as in progress but doesn't have an assignee. Is someone working on this?

**Comment by pdg744** [comment]
Closing this as it's a duplicate

**Comment by tzerrell** [comment]
Archiving as this is is closed due to duplication, not completed work.
