### ISSUE TITLE
Fix rust verifier to correctly verify the code being run

### ISSUE THREAD

**Issue by jbruestle** [risc0/risc0#89]
Currently https://github.com/risc0/risc0/blob/main/risc0/zkvm/verify/src/circuit.rs is missing the code required to verify which method is being run (which the C++ has).

**Comment by flaub** [comment]
Users may see this error in the log:

> new_game: JsValue(Error: {"index":0,"kind":{"ExecutionError":"Smart contract panicked: panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', src/lib.rs:49:62"}} TypedError@https://cdn.jsdelivr.net/npm/near-api-js@0.41.0/dist/near-api-js.js:3269:9 ServerError@https://cdn.jsdelivr.net/npm/near-api-js@0.41.0/dist/near-api-js.js:3595:1 ServerTransactionError@https://cdn.jsdelivr.net/npm/near-api-js@0.41.0/dist/near-api-js.js:3598:1 parseResultError@https://cdn.jsdelivr.net/npm/near-api-js@0.41.0/dist/near-api-js.js:3611:29 signAndSendTransactionV2@https://cdn.jsdelivr.net/npm/near-api-js@0.41.0/dist/near-api-js.js:163:36 )
