### ISSUE TITLE
Add feature- & platform-specific Rust docs

### ISSUE THREAD

**Issue by tzerrell** [risc0/risc0#919]
Expand our Rust docs with documentation for code that is enabled only when certain features are turned on, or on certain platforms. Look at https://docs.rs/tokio/latest/tokio/ for an example.

**Comment by austinabell** [comment]
The `[package.metadata.docs.rs]` section is how you can control what is run with docs.rs. https://github.com/tokio-rs/tokio/blob/4aa7bbff4c70b7c43c931b1e18af5048da191f40/tokio/Cargo.toml#L157 is the section for tokio.

You can also be specific around which targets are compiled, but unclear how nicely that will play with the custom target https://blog.rust-lang.org/2020/03/15/docs-rs-opt-into-fewer-targets.html. There might be a hacky workaround where you install the toolchain in a build script when [`DOCS_RS`](https://docs.rs/about/builds#detecting-docsrs) env variable is set, but unclear if you will be able to build docs for this custom toolchain.

**Comment by nategraf** [comment]
> The [`[package.metadata.docs.rs]`](https://docs.rs/about/metadata) section is how you can control what is run with docs.rs. https://github.com/tokio-rs/tokio/blob/4aa7bbff4c70b7c43c931b1e18af5048da191f40/tokio/Cargo.toml#L157 is the section for tokio.
> 
> You can also be specific around which targets are compiled, but unclear how nicely that will play with the custom target https://blog.rust-lang.org/2020/03/15/docs-rs-opt-into-fewer-targets.html. There might be a hacky workaround where you install the toolchain in a build script when [`DOCS_RS`](https://docs.rs/about/builds#detecting-docsrs) env variable is set, but unclear if you will be able to build docs for this custom toolchain.

So, to get 80% of the value here I don't think we need to build for the `rv32im-risc0-zkvm-elf` target. Without it, we'll be missing the guest methods, but we can still get the host methods that are not currently documented.
