### ISSUE TITLE
note on installation on macOS with aarch64 chips

### ISSUE THREAD

**Issue by weikengchen** [risc0/risc0#942]
This issue is a note for future reference about installing cargo-risczero on aarch64.

1. need to make sure that the default host and the default toolchain are both aarch64. One can check this by 

```console
rustup show
```

To change the default host to `aarch64-apple-darwin`, do: 
```console
rustup set default-host aarch64-apple-darwin
```

To change the default toolchain to `stable-aarch64-apple-darwin`, do:
```console
rustup default stable-aarch64-apple-darwin
```

2. a very classic issue that could happen for macOS is that macOS may have two iconv libraries with different syntax. There are some GitHub issues and Stackoverflow ones around this. 

https://stackoverflow.com/questions/57734434/libiconv-or-iconv-undefined-symbol-on-mac-osx
https://github.com/rust-lang/git2-rs/issues/263

The idea is that machines with iconv library installed from MacPorts will cause this issue. It appears that the most reliable solution is to deactivate this iconv library in MacPorts (and install one from Homebrew). After the compilation of cargo-risczero is done, one may consider reverting the changes. (See the link above for more detail)

```console
sudo port deactivate libiconv
```

3. some dependencies appear to be needed to compile cargo-risczero. 

In my case, I used Homebrew to install libiconv, openssl, and pkgconf.

----

My opinion is that the need to handle these dependency issues could be a routine thing once Bonsai is in public beta. So, maybe the team wants to see if there is a nice way to remove all hurdles that may happen to developers (package dependencies, particularly in macOS, are never fun).

I do not know if cargo-risczero must have these dependencies, or that it is a side effect of other crates---I feel that it benefits to reduce the dependencies of cargo-risczero and let it be a downloader of the binary. If, in the event that it needs to compile R0's Rust from scratch, it can pull a precompiled binary that does so.

**Comment by flaub** [comment]
Thank you for this, this is great!

We're actually working on what we call 'binary distributions' which should alleviate much (but probably not all) of the above issues. Basically the idea is to have prebuilt binaries for all the major platforms so that devs don't need to build the zkvm from scratch. But we will still support this mode for users that need it.

I'm hoping to land this functionality by the next `0.19` release.

**Comment by weikengchen** [comment]
(How do you reply to messages this quickly)

But, thanks! I am on my way to benchmark something with Bonsai. Expect the Bonsai API server to have some work to do after its dinner :)

**Comment by pdg744** [comment]
> (How do you reply to messages this quickly) 

Very common question :-D

**Comment by weikengchen** [comment]
Close since the new version has resolved this issue.
