### ISSUE TITLE
Rebase the fault checker work on composition

### ISSUE THREAD

**Issue by nategraf** [risc0/risc0#990]
The fault checker, merged in https://github.com/risc0/risc0/pull/920, was originally implemented without composition by modifying the prover and verifier logic to accept the fault checker execution as a final segment tacted onto the end of a `Session`. It was recognized before completing the fault checker work that we would like to rebase this onto composition when it is available. This issue tracks that work.

Related: #980, #981

**Comment by SchmErik** [comment]
we've talked about this internally and decided to hold off on implementing fault proofs until a future revision of the circuit. Closing.
