### ISSUE TITLE
Build updated riscv32im toolchain

### ISSUE THREAD

**Issue by flaub** [risc0/risc0#997]
* Include clippy
* Try to use latest stable rust
* See: https://risc0.slack.com/archives/C02QCC71SC8/p1697504636934259?thread_ts=1692930831.318869&cid=C02QCC71SC8
* Build against older glibc (for wider Linux distro compat)

**Comment by SchmErik** [comment]
notes: latest stable rust patched with the illegal instruction fix and a potentially hacky and incorrect assembly parser fix generates guest code that generates code that reaches into lower parts of memory and fails.
