### ISSUE TITLE
Deprecate metal due to recent MTLCompilerService limitations

### ISSUE THREAD

**Issue by flaub** [risc0/risc0#999]
See: #937 

The `metal` HAL on recent versions of macOS fail to compile due to new limitations on the number of temporary registers allowed in a given function. There doesn't seem to be any easy/low cost way to fix the code generator for `eval_check`, so our best option at this time is to deprecate Metal support and hope that:
1. Apple raises the limitation in a future macOS release
2. New zirgen compiler will be able to produce a more structured function that doesn't require so many outstanding registers at any given time.

**Comment by flaub** [comment]
https://developer.apple.com/forums/thread/712889

**Comment by flaub** [comment]
AFAIK, this failure occurs on M1 and M2. It seems to work if you happen to have an older version of the Metal compiler. We have a caching system that attempts to avoid long compile times, but this cache might make it seem that things are working even on newer versions.

**Comment by flaub** [comment]
Metal seems to be working in latest macOS again.

**Comment by weikengchen** [comment]
That is good news!
